/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.indexes


import ch.yass.db.tables.ContinuityContainers
import ch.yass.db.tables.CourierMessages
import ch.yass.db.tables.Identities
import ch.yass.db.tables.IdentityCredentialIdentifiers
import ch.yass.db.tables.IdentityCredentialTypes
import ch.yass.db.tables.IdentityCredentials
import ch.yass.db.tables.IdentityRecoveryAddresses
import ch.yass.db.tables.IdentityRecoveryCodes
import ch.yass.db.tables.IdentityRecoveryTokens
import ch.yass.db.tables.IdentityVerifiableAddresses
import ch.yass.db.tables.IdentityVerificationCodes
import ch.yass.db.tables.IdentityVerificationTokens
import ch.yass.db.tables.SchemaVersion
import ch.yass.db.tables.SelfserviceErrors
import ch.yass.db.tables.SelfserviceLoginFlows
import ch.yass.db.tables.SelfserviceRecoveryFlows
import ch.yass.db.tables.SelfserviceRegistrationFlows
import ch.yass.db.tables.SelfserviceSettingsFlows
import ch.yass.db.tables.SelfserviceVerificationFlows
import ch.yass.db.tables.SessionDevices
import ch.yass.db.tables.Sessions

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val CONTINUITY_CONTAINERS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("continuity_containers_id_nid_idx"), ContinuityContainers.CONTINUITY_CONTAINERS, arrayOf(ContinuityContainers.CONTINUITY_CONTAINERS.ID, ContinuityContainers.CONTINUITY_CONTAINERS.NID), false)
val CONTINUITY_CONTAINERS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("continuity_containers_nid_id_idx"), ContinuityContainers.CONTINUITY_CONTAINERS, arrayOf(ContinuityContainers.CONTINUITY_CONTAINERS.NID, ContinuityContainers.CONTINUITY_CONTAINERS.ID), false)
val COURIER_MESSAGES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("courier_messages_id_nid_idx"), CourierMessages.COURIER_MESSAGES, arrayOf(CourierMessages.COURIER_MESSAGES.ID, CourierMessages.COURIER_MESSAGES.NID), false)
val COURIER_MESSAGES_NID_ID_IDX: Index = Internal.createIndex(DSL.name("courier_messages_nid_id_idx"), CourierMessages.COURIER_MESSAGES, arrayOf(CourierMessages.COURIER_MESSAGES.NID, CourierMessages.COURIER_MESSAGES.ID), false)
val COURIER_MESSAGES_STATUS_IDX: Index = Internal.createIndex(DSL.name("courier_messages_status_idx"), CourierMessages.COURIER_MESSAGES, arrayOf(CourierMessages.COURIER_MESSAGES.STATUS), false)
val IDENTITIES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identities_id_nid_idx"), Identities.IDENTITIES, arrayOf(Identities.IDENTITIES.ID, Identities.IDENTITIES.NID), false)
val IDENTITIES_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identities_nid_id_idx"), Identities.IDENTITIES, arrayOf(Identities.IDENTITIES.NID, Identities.IDENTITIES.ID), false)
val IDENTITY_CREDENTIAL_IDENTIFIERS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_credential_identifiers_id_nid_idx"), IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS, arrayOf(IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.ID, IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.NID), false)
val IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTIFIER_NID_TYPE_UQ_IDX: Index = Internal.createIndex(DSL.name("identity_credential_identifiers_identifier_nid_type_uq_idx"), IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS, arrayOf(IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.NID, IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTITY_CREDENTIAL_TYPE_ID, IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTIFIER), true)
val IDENTITY_CREDENTIAL_IDENTIFIERS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_credential_identifiers_nid_id_idx"), IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS, arrayOf(IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.NID, IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.ID), false)
val IDENTITY_CREDENTIAL_IDENTIFIERS_NID_IDENTITY_CREDENTIAL_ID_IDX: Index = Internal.createIndex(DSL.name("identity_credential_identifiers_nid_identity_credential_id_idx"), IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS, arrayOf(IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTITY_CREDENTIAL_ID, IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.NID), false)
val IDENTITY_CREDENTIAL_TYPES_NAME_IDX: Index = Internal.createIndex(DSL.name("identity_credential_types_name_idx"), IdentityCredentialTypes.IDENTITY_CREDENTIAL_TYPES, arrayOf(IdentityCredentialTypes.IDENTITY_CREDENTIAL_TYPES.NAME), true)
val IDENTITY_CREDENTIALS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_credentials_id_nid_idx"), IdentityCredentials.IDENTITY_CREDENTIALS, arrayOf(IdentityCredentials.IDENTITY_CREDENTIALS.ID, IdentityCredentials.IDENTITY_CREDENTIALS.NID), false)
val IDENTITY_CREDENTIALS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_credentials_nid_id_idx"), IdentityCredentials.IDENTITY_CREDENTIALS, arrayOf(IdentityCredentials.IDENTITY_CREDENTIALS.NID, IdentityCredentials.IDENTITY_CREDENTIALS.ID), false)
val IDENTITY_CREDENTIALS_NID_IDENTITY_ID_IDX: Index = Internal.createIndex(DSL.name("identity_credentials_nid_identity_id_idx"), IdentityCredentials.IDENTITY_CREDENTIALS, arrayOf(IdentityCredentials.IDENTITY_CREDENTIALS.IDENTITY_ID, IdentityCredentials.IDENTITY_CREDENTIALS.NID), false)
val IDENTITY_RECOVERY_ADDRESSES_CODE_UQ_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_code_uq_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.TOKEN), true)
val IDENTITY_RECOVERY_ADDRESSES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_id_nid_idx"), IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES, arrayOf(IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.ID, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.NID), false)
val IDENTITY_RECOVERY_ADDRESSES_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_nid_id_idx"), IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES, arrayOf(IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.NID, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.ID), false)
val IDENTITY_RECOVERY_ADDRESSES_NID_IDENTITY_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_nid_identity_id_idx"), IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES, arrayOf(IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.IDENTITY_ID, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.NID), false)
val IDENTITY_RECOVERY_ADDRESSES_STATUS_VIA_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_status_via_idx"), IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES, arrayOf(IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.NID, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.VIA, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.VALUE), false)
val IDENTITY_RECOVERY_ADDRESSES_STATUS_VIA_UQ_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_addresses_status_via_uq_idx"), IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES, arrayOf(IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.NID, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.VIA, IdentityRecoveryAddresses.IDENTITY_RECOVERY_ADDRESSES.VALUE), true)
val IDENTITY_RECOVERY_CODES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_codes_id_nid_idx"), IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES, arrayOf(IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES.ID, IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES.NID), false)
val IDENTITY_RECOVERY_CODES_NID_FLOW_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_codes_nid_flow_id_idx"), IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES, arrayOf(IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES.NID, IdentityRecoveryCodes.IDENTITY_RECOVERY_CODES.SELFSERVICE_RECOVERY_FLOW_ID), false)
val IDENTITY_RECOVERY_TOKENS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_tokens_id_nid_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.ID, IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.NID), false)
val IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_tokens_identity_recovery_address_id_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.IDENTITY_RECOVERY_ADDRESS_ID), false)
val IDENTITY_RECOVERY_TOKENS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_tokens_nid_id_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.NID, IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.ID), false)
val IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_FLOW_ID_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_tokens_selfservice_recovery_flow_id_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.SELFSERVICE_RECOVERY_FLOW_ID), false)
val IDENTITY_RECOVERY_TOKENS_TOKEN_NID_USED_IDX: Index = Internal.createIndex(DSL.name("identity_recovery_tokens_token_nid_used_idx"), IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS, arrayOf(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.NID, IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.TOKEN, IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.USED), false)
val IDENTITY_VERIFIABLE_ADDRESSES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_verifiable_addresses_id_nid_idx"), IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES, arrayOf(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.ID, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID), false)
val IDENTITY_VERIFIABLE_ADDRESSES_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verifiable_addresses_nid_id_idx"), IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES, arrayOf(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.ID), false)
val IDENTITY_VERIFIABLE_ADDRESSES_NID_IDENTITY_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verifiable_addresses_nid_identity_id_idx"), IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES, arrayOf(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.IDENTITY_ID, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID), false)
val IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_IDX: Index = Internal.createIndex(DSL.name("identity_verifiable_addresses_status_via_idx"), IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES, arrayOf(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VIA, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VALUE), false)
val IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_UQ_IDX: Index = Internal.createIndex(DSL.name("identity_verifiable_addresses_status_via_uq_idx"), IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES, arrayOf(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VIA, IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VALUE), true)
val IDENTITY_VERIFICATION_CODES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_codes_id_nid_idx"), IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES, arrayOf(IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.ID, IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.NID), false)
val IDENTITY_VERIFICATION_CODES_NID_FLOW_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_codes_nid_flow_id_idx"), IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES, arrayOf(IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.NID, IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.SELFSERVICE_VERIFICATION_FLOW_ID), false)
val IDENTITY_VERIFICATION_TOKENS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_id_nid_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.ID, IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.NID), false)
val IDENTITY_VERIFICATION_TOKENS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_nid_id_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.NID, IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.ID), false)
val IDENTITY_VERIFICATION_TOKENS_TOKEN_NID_USED_FLOW_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_token_nid_used_flow_id_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.NID, IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.TOKEN, IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.USED, IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.SELFSERVICE_VERIFICATION_FLOW_ID), false)
val IDENTITY_VERIFICATION_TOKENS_TOKEN_UQ_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_token_uq_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.TOKEN), true)
val IDENTITY_VERIFICATION_TOKENS_VERIFIABLE_ADDRESS_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_verifiable_address_id_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.IDENTITY_VERIFIABLE_ADDRESS_ID), false)
val IDENTITY_VERIFICATION_TOKENS_VERIFICATION_FLOW_ID_IDX: Index = Internal.createIndex(DSL.name("identity_verification_tokens_verification_flow_id_idx"), IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS, arrayOf(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.SELFSERVICE_VERIFICATION_FLOW_ID), false)
val SCHEMA_VERSION_IR_IDX: Index = Internal.createIndex(DSL.name("schema_version_ir_idx"), SchemaVersion.SCHEMA_VERSION, arrayOf(SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK), false)
val SCHEMA_VERSION_S_IDX: Index = Internal.createIndex(DSL.name("schema_version_s_idx"), SchemaVersion.SCHEMA_VERSION, arrayOf(SchemaVersion.SCHEMA_VERSION.SUCCESS), false)
val SCHEMA_VERSION_VR_IDX: Index = Internal.createIndex(DSL.name("schema_version_vr_idx"), SchemaVersion.SCHEMA_VERSION, arrayOf(SchemaVersion.SCHEMA_VERSION.VERSION_RANK), false)
val SELFSERVICE_ERRORS_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_errors_nid_idx"), SelfserviceErrors.SELFSERVICE_ERRORS, arrayOf(SelfserviceErrors.SELFSERVICE_ERRORS.ID, SelfserviceErrors.SELFSERVICE_ERRORS.NID), false)
val SELFSERVICE_LOGIN_FLOWS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_login_flows_id_nid_idx"), SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS, arrayOf(SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.ID, SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.NID), false)
val SELFSERVICE_LOGIN_FLOWS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("selfservice_login_flows_nid_id_idx"), SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS, arrayOf(SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.NID, SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.ID), false)
val SELFSERVICE_RECOVERY_FLOWS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_recovery_flows_id_nid_idx"), SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS, arrayOf(SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS.ID, SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS.NID), false)
val SELFSERVICE_RECOVERY_FLOWS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("selfservice_recovery_flows_nid_id_idx"), SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS, arrayOf(SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS.NID, SelfserviceRecoveryFlows.SELFSERVICE_RECOVERY_FLOWS.ID), false)
val SELFSERVICE_REGISTRATION_FLOWS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_registration_flows_id_nid_idx"), SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS, arrayOf(SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.ID, SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.NID), false)
val SELFSERVICE_REGISTRATION_FLOWS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("selfservice_registration_flows_nid_id_idx"), SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS, arrayOf(SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.NID, SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.ID), false)
val SELFSERVICE_SETTINGS_FLOWS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_settings_flows_id_nid_idx"), SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS, arrayOf(SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS.ID, SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS.NID), false)
val SELFSERVICE_SETTINGS_FLOWS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("selfservice_settings_flows_nid_id_idx"), SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS, arrayOf(SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS.NID, SelfserviceSettingsFlows.SELFSERVICE_SETTINGS_FLOWS.ID), false)
val SELFSERVICE_VERIFICATION_FLOWS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("selfservice_verification_flows_id_nid_idx"), SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS, arrayOf(SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS.ID, SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS.NID), false)
val SELFSERVICE_VERIFICATION_FLOWS_NID_ID_IDX: Index = Internal.createIndex(DSL.name("selfservice_verification_flows_nid_id_idx"), SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS, arrayOf(SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS.NID, SelfserviceVerificationFlows.SELFSERVICE_VERIFICATION_FLOWS.ID), false)
val SESSION_DEVICES_ID_NID_IDX: Index = Internal.createIndex(DSL.name("session_devices_id_nid_idx"), SessionDevices.SESSION_DEVICES, arrayOf(SessionDevices.SESSION_DEVICES.ID, SessionDevices.SESSION_DEVICES.NID), false)
val SESSION_DEVICES_SESSION_ID_NID_IDX: Index = Internal.createIndex(DSL.name("session_devices_session_id_nid_idx"), SessionDevices.SESSION_DEVICES, arrayOf(SessionDevices.SESSION_DEVICES.SESSION_ID, SessionDevices.SESSION_DEVICES.NID), false)
val SESSIONS_ID_NID_IDX: Index = Internal.createIndex(DSL.name("sessions_id_nid_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.ID, Sessions.SESSIONS.NID), false)
val SESSIONS_IDENTITY_ID_NID_IDX: Index = Internal.createIndex(DSL.name("sessions_identity_id_nid_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.IDENTITY_ID, Sessions.SESSIONS.NID), false)
val SESSIONS_LOGOUT_TOKEN_UQ_IDX: Index = Internal.createIndex(DSL.name("sessions_logout_token_uq_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.LOGOUT_TOKEN), true)
val SESSIONS_NID_ID_IDENTITY_ID_IDX: Index = Internal.createIndex(DSL.name("sessions_nid_id_identity_id_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.NID, Sessions.SESSIONS.IDENTITY_ID, Sessions.SESSIONS.ID), false)
val SESSIONS_TOKEN_NID_IDX: Index = Internal.createIndex(DSL.name("sessions_token_nid_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.NID, Sessions.SESSIONS.TOKEN), false)
val SESSIONS_TOKEN_UQ_IDX: Index = Internal.createIndex(DSL.name("sessions_token_uq_idx"), Sessions.SESSIONS, arrayOf(Sessions.SESSIONS.TOKEN), true)
