/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class IdentityCredentials(
    var id: UUID? = null,
    var config: JSONB? = null,
    var identityCredentialTypeId: UUID? = null,
    var identityId: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var nid: UUID? = null,
    var version: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: IdentityCredentials = other as IdentityCredentials
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.config === null) {
            if (o.config !== null)
                return false
        }
        else if (this.config != o.config)
            return false
        if (this.identityCredentialTypeId === null) {
            if (o.identityCredentialTypeId !== null)
                return false
        }
        else if (this.identityCredentialTypeId != o.identityCredentialTypeId)
            return false
        if (this.identityId === null) {
            if (o.identityId !== null)
                return false
        }
        else if (this.identityId != o.identityId)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        if (this.version === null) {
            if (o.version !== null)
                return false
        }
        else if (this.version != o.version)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.config === null) 0 else this.config.hashCode())
        result = prime * result + (if (this.identityCredentialTypeId === null) 0 else this.identityCredentialTypeId.hashCode())
        result = prime * result + (if (this.identityId === null) 0 else this.identityId.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        result = prime * result + (if (this.version === null) 0 else this.version.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("IdentityCredentials (")

        sb.append(id)
        sb.append(", ").append(config)
        sb.append(", ").append(identityCredentialTypeId)
        sb.append(", ").append(identityId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(nid)
        sb.append(", ").append(version)

        sb.append(")")
        return sb.toString()
    }
}
