/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class IdentityVerifiableAddresses(
    var id: UUID? = null,
    var status: String? = null,
    var via: String? = null,
    var verified: Boolean? = null,
    var value: String? = null,
    var verifiedAt: LocalDateTime? = null,
    var identityId: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var nid: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: IdentityVerifiableAddresses = other as IdentityVerifiableAddresses
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.status === null) {
            if (o.status !== null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.via === null) {
            if (o.via !== null)
                return false
        }
        else if (this.via != o.via)
            return false
        if (this.verified === null) {
            if (o.verified !== null)
                return false
        }
        else if (this.verified != o.verified)
            return false
        if (this.value === null) {
            if (o.value !== null)
                return false
        }
        else if (this.value != o.value)
            return false
        if (this.verifiedAt === null) {
            if (o.verifiedAt !== null)
                return false
        }
        else if (this.verifiedAt != o.verifiedAt)
            return false
        if (this.identityId === null) {
            if (o.identityId !== null)
                return false
        }
        else if (this.identityId != o.identityId)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.status === null) 0 else this.status.hashCode())
        result = prime * result + (if (this.via === null) 0 else this.via.hashCode())
        result = prime * result + (if (this.verified === null) 0 else this.verified.hashCode())
        result = prime * result + (if (this.value === null) 0 else this.value.hashCode())
        result = prime * result + (if (this.verifiedAt === null) 0 else this.verifiedAt.hashCode())
        result = prime * result + (if (this.identityId === null) 0 else this.identityId.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("IdentityVerifiableAddresses (")

        sb.append(id)
        sb.append(", ").append(status)
        sb.append(", ").append(via)
        sb.append(", ").append(verified)
        sb.append(", ").append(value)
        sb.append(", ").append(verifiedAt)
        sb.append(", ").append(identityId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(nid)

        sb.append(")")
        return sb.toString()
    }
}
