/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class IdentityRecoveryCodes(
    var id: UUID? = null,
    var code: String? = null,
    var usedAt: LocalDateTime? = null,
    var identityRecoveryAddressId: UUID? = null,
    var codeType: Int? = null,
    var expiresAt: LocalDateTime? = null,
    var issuedAt: LocalDateTime? = null,
    var selfserviceRecoveryFlowId: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var nid: UUID? = null,
    var identityId: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: IdentityRecoveryCodes = other as IdentityRecoveryCodes
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.code === null) {
            if (o.code !== null)
                return false
        }
        else if (this.code != o.code)
            return false
        if (this.usedAt === null) {
            if (o.usedAt !== null)
                return false
        }
        else if (this.usedAt != o.usedAt)
            return false
        if (this.identityRecoveryAddressId === null) {
            if (o.identityRecoveryAddressId !== null)
                return false
        }
        else if (this.identityRecoveryAddressId != o.identityRecoveryAddressId)
            return false
        if (this.codeType === null) {
            if (o.codeType !== null)
                return false
        }
        else if (this.codeType != o.codeType)
            return false
        if (this.expiresAt === null) {
            if (o.expiresAt !== null)
                return false
        }
        else if (this.expiresAt != o.expiresAt)
            return false
        if (this.issuedAt === null) {
            if (o.issuedAt !== null)
                return false
        }
        else if (this.issuedAt != o.issuedAt)
            return false
        if (this.selfserviceRecoveryFlowId === null) {
            if (o.selfserviceRecoveryFlowId !== null)
                return false
        }
        else if (this.selfserviceRecoveryFlowId != o.selfserviceRecoveryFlowId)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        if (this.identityId === null) {
            if (o.identityId !== null)
                return false
        }
        else if (this.identityId != o.identityId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.code === null) 0 else this.code.hashCode())
        result = prime * result + (if (this.usedAt === null) 0 else this.usedAt.hashCode())
        result = prime * result + (if (this.identityRecoveryAddressId === null) 0 else this.identityRecoveryAddressId.hashCode())
        result = prime * result + (if (this.codeType === null) 0 else this.codeType.hashCode())
        result = prime * result + (if (this.expiresAt === null) 0 else this.expiresAt.hashCode())
        result = prime * result + (if (this.issuedAt === null) 0 else this.issuedAt.hashCode())
        result = prime * result + (if (this.selfserviceRecoveryFlowId === null) 0 else this.selfserviceRecoveryFlowId.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        result = prime * result + (if (this.identityId === null) 0 else this.identityId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("IdentityRecoveryCodes (")

        sb.append(id)
        sb.append(", ").append(code)
        sb.append(", ").append(usedAt)
        sb.append(", ").append(identityRecoveryAddressId)
        sb.append(", ").append(codeType)
        sb.append(", ").append(expiresAt)
        sb.append(", ").append(issuedAt)
        sb.append(", ").append(selfserviceRecoveryFlowId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(nid)
        sb.append(", ").append(identityId)

        sb.append(")")
        return sb.toString()
    }
}
