/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class IdentityVerificationTokens(
    var id: UUID? = null,
    var token: String? = null,
    var used: Boolean? = null,
    var usedAt: LocalDateTime? = null,
    var expiresAt: LocalDateTime? = null,
    var issuedAt: LocalDateTime? = null,
    var identityVerifiableAddressId: UUID? = null,
    var selfserviceVerificationFlowId: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var nid: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: IdentityVerificationTokens = other as IdentityVerificationTokens
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.token === null) {
            if (o.token !== null)
                return false
        }
        else if (this.token != o.token)
            return false
        if (this.used === null) {
            if (o.used !== null)
                return false
        }
        else if (this.used != o.used)
            return false
        if (this.usedAt === null) {
            if (o.usedAt !== null)
                return false
        }
        else if (this.usedAt != o.usedAt)
            return false
        if (this.expiresAt === null) {
            if (o.expiresAt !== null)
                return false
        }
        else if (this.expiresAt != o.expiresAt)
            return false
        if (this.issuedAt === null) {
            if (o.issuedAt !== null)
                return false
        }
        else if (this.issuedAt != o.issuedAt)
            return false
        if (this.identityVerifiableAddressId === null) {
            if (o.identityVerifiableAddressId !== null)
                return false
        }
        else if (this.identityVerifiableAddressId != o.identityVerifiableAddressId)
            return false
        if (this.selfserviceVerificationFlowId === null) {
            if (o.selfserviceVerificationFlowId !== null)
                return false
        }
        else if (this.selfserviceVerificationFlowId != o.selfserviceVerificationFlowId)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.token === null) 0 else this.token.hashCode())
        result = prime * result + (if (this.used === null) 0 else this.used.hashCode())
        result = prime * result + (if (this.usedAt === null) 0 else this.usedAt.hashCode())
        result = prime * result + (if (this.expiresAt === null) 0 else this.expiresAt.hashCode())
        result = prime * result + (if (this.issuedAt === null) 0 else this.issuedAt.hashCode())
        result = prime * result + (if (this.identityVerifiableAddressId === null) 0 else this.identityVerifiableAddressId.hashCode())
        result = prime * result + (if (this.selfserviceVerificationFlowId === null) 0 else this.selfserviceVerificationFlowId.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("IdentityVerificationTokens (")

        sb.append(id)
        sb.append(", ").append(token)
        sb.append(", ").append(used)
        sb.append(", ").append(usedAt)
        sb.append(", ").append(expiresAt)
        sb.append(", ").append(issuedAt)
        sb.append(", ").append(identityVerifiableAddressId)
        sb.append(", ").append(selfserviceVerificationFlowId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(nid)

        sb.append(")")
        return sb.toString()
    }
}
