/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SchemaMigration(
    var version: String? = null,
    var versionSelf: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: SchemaMigration = other as SchemaMigration
        if (this.version === null) {
            if (o.version !== null)
                return false
        }
        else if (this.version != o.version)
            return false
        if (this.versionSelf === null) {
            if (o.versionSelf !== null)
                return false
        }
        else if (this.versionSelf != o.versionSelf)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.version === null) 0 else this.version.hashCode())
        result = prime * result + (if (this.versionSelf === null) 0 else this.versionSelf.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("SchemaMigration (")

        sb.append(version)
        sb.append(", ").append(versionSelf)

        sb.append(")")
        return sb.toString()
    }
}
