/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SelfserviceErrors(
    var id: UUID? = null,
    var errors: JSONB? = null,
    var seenAt: LocalDateTime? = null,
    var wasSeen: Boolean? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var csrfToken: String? = null,
    var nid: UUID? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: SelfserviceErrors = other as SelfserviceErrors
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.errors === null) {
            if (o.errors !== null)
                return false
        }
        else if (this.errors != o.errors)
            return false
        if (this.seenAt === null) {
            if (o.seenAt !== null)
                return false
        }
        else if (this.seenAt != o.seenAt)
            return false
        if (this.wasSeen === null) {
            if (o.wasSeen !== null)
                return false
        }
        else if (this.wasSeen != o.wasSeen)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.csrfToken === null) {
            if (o.csrfToken !== null)
                return false
        }
        else if (this.csrfToken != o.csrfToken)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.errors === null) 0 else this.errors.hashCode())
        result = prime * result + (if (this.seenAt === null) 0 else this.seenAt.hashCode())
        result = prime * result + (if (this.wasSeen === null) 0 else this.wasSeen.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.csrfToken === null) 0 else this.csrfToken.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("SelfserviceErrors (")

        sb.append(id)
        sb.append(", ").append(errors)
        sb.append(", ").append(seenAt)
        sb.append(", ").append(wasSeen)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(csrfToken)
        sb.append(", ").append(nid)

        sb.append(")")
        return sb.toString()
    }
}
