/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SessionDevices(
    var id: UUID? = null,
    var ipAddress: String? = null,
    var userAgent: String? = null,
    var location: String? = null,
    var nid: UUID? = null,
    var sessionId: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: SessionDevices = other as SessionDevices
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.ipAddress === null) {
            if (o.ipAddress !== null)
                return false
        }
        else if (this.ipAddress != o.ipAddress)
            return false
        if (this.userAgent === null) {
            if (o.userAgent !== null)
                return false
        }
        else if (this.userAgent != o.userAgent)
            return false
        if (this.location === null) {
            if (o.location !== null)
                return false
        }
        else if (this.location != o.location)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        if (this.sessionId === null) {
            if (o.sessionId !== null)
                return false
        }
        else if (this.sessionId != o.sessionId)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.ipAddress === null) 0 else this.ipAddress.hashCode())
        result = prime * result + (if (this.userAgent === null) 0 else this.userAgent.hashCode())
        result = prime * result + (if (this.location === null) 0 else this.location.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        result = prime * result + (if (this.sessionId === null) 0 else this.sessionId.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("SessionDevices (")

        sb.append(id)
        sb.append(", ").append(ipAddress)
        sb.append(", ").append(userAgent)
        sb.append(", ").append(location)
        sb.append(", ").append(nid)
        sb.append(", ").append(sessionId)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
