/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.references


import ch.yass.db.tables.FlywaySchemaHistory
import ch.yass.db.tables.Game
import ch.yass.db.tables.Hand
import ch.yass.db.tables.Player
import ch.yass.db.tables.Seat
import ch.yass.db.tables.Trick



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.game</code>.
 */
val GAME: Game = Game.GAME

/**
 * The table <code>public.hand</code>.
 */
val HAND: Hand = Hand.HAND

/**
 * The table <code>public.player</code>.
 */
val PLAYER: Player = Player.PLAYER

/**
 * The table <code>public.seat</code>.
 */
val SEAT: Seat = Seat.SEAT

/**
 * The table <code>public.trick</code>.
 */
val TRICK: Trick = Trick.TRICK
