/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.CourierMessageDispatches

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.JSON
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourierMessageDispatchesRecord() : UpdatableRecordImpl<CourierMessageDispatchesRecord>(CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES), Record7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var messageId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var status: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var error: JSON?
        set(value): Unit = set(3, value)
        get(): JSON? = get(3) as JSON?

    open var nid: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<UUID?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.ID
    override fun field2(): Field<UUID?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.MESSAGE_ID
    override fun field3(): Field<String?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.STATUS
    override fun field4(): Field<JSON?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.ERROR
    override fun field5(): Field<UUID?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.NID
    override fun field6(): Field<LocalDateTime?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.CREATED_AT
    override fun field7(): Field<LocalDateTime?> = CourierMessageDispatches.COURIER_MESSAGE_DISPATCHES.UPDATED_AT
    override fun component1(): UUID? = id
    override fun component2(): UUID? = messageId
    override fun component3(): String? = status
    override fun component4(): JSON? = error
    override fun component5(): UUID? = nid
    override fun component6(): LocalDateTime? = createdAt
    override fun component7(): LocalDateTime? = updatedAt
    override fun value1(): UUID? = id
    override fun value2(): UUID? = messageId
    override fun value3(): String? = status
    override fun value4(): JSON? = error
    override fun value5(): UUID? = nid
    override fun value6(): LocalDateTime? = createdAt
    override fun value7(): LocalDateTime? = updatedAt

    override fun value1(value: UUID?): CourierMessageDispatchesRecord {
        this.id = value
        return this
    }

    override fun value2(value: UUID?): CourierMessageDispatchesRecord {
        this.messageId = value
        return this
    }

    override fun value3(value: String?): CourierMessageDispatchesRecord {
        this.status = value
        return this
    }

    override fun value4(value: JSON?): CourierMessageDispatchesRecord {
        this.error = value
        return this
    }

    override fun value5(value: UUID?): CourierMessageDispatchesRecord {
        this.nid = value
        return this
    }

    override fun value6(value: LocalDateTime?): CourierMessageDispatchesRecord {
        this.createdAt = value
        return this
    }

    override fun value7(value: LocalDateTime?): CourierMessageDispatchesRecord {
        this.updatedAt = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: String?, value4: JSON?, value5: UUID?, value6: LocalDateTime?, value7: LocalDateTime?): CourierMessageDispatchesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised CourierMessageDispatchesRecord
     */
    constructor(id: UUID? = null, messageId: UUID? = null, status: String? = null, error: JSON? = null, nid: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.messageId = messageId
        this.status = status
        this.error = error
        this.nid = nid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
    }

    /**
     * Create a detached, initialised CourierMessageDispatchesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.CourierMessageDispatches?): this() {
        if (value != null) {
            this.id = value.id
            this.messageId = value.messageId
            this.status = value.status
            this.error = value.error
            this.nid = value.nid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
        }
    }
}
