/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.CourierMessages

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record12
import org.jooq.Row12
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourierMessagesRecord() : UpdatableRecordImpl<CourierMessagesRecord>(CourierMessages.COURIER_MESSAGES), Record12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var type: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var status: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var body: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var subject: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var recipient: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var templateType: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var templateData: ByteArray?
        set(value): Unit = set(9, value)
        get(): ByteArray? = get(9) as ByteArray?

    open var nid: UUID?
        set(value): Unit = set(10, value)
        get(): UUID? = get(10) as UUID?

    open var sendCount: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?> = super.fieldsRow() as Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?>
    override fun valuesRow(): Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?> = super.valuesRow() as Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?>
    override fun field1(): Field<UUID?> = CourierMessages.COURIER_MESSAGES.ID
    override fun field2(): Field<Int?> = CourierMessages.COURIER_MESSAGES.TYPE
    override fun field3(): Field<Int?> = CourierMessages.COURIER_MESSAGES.STATUS
    override fun field4(): Field<String?> = CourierMessages.COURIER_MESSAGES.BODY
    override fun field5(): Field<String?> = CourierMessages.COURIER_MESSAGES.SUBJECT
    override fun field6(): Field<String?> = CourierMessages.COURIER_MESSAGES.RECIPIENT
    override fun field7(): Field<LocalDateTime?> = CourierMessages.COURIER_MESSAGES.CREATED_AT
    override fun field8(): Field<LocalDateTime?> = CourierMessages.COURIER_MESSAGES.UPDATED_AT
    override fun field9(): Field<String?> = CourierMessages.COURIER_MESSAGES.TEMPLATE_TYPE
    override fun field10(): Field<ByteArray?> = CourierMessages.COURIER_MESSAGES.TEMPLATE_DATA
    override fun field11(): Field<UUID?> = CourierMessages.COURIER_MESSAGES.NID
    override fun field12(): Field<Int?> = CourierMessages.COURIER_MESSAGES.SEND_COUNT
    override fun component1(): UUID? = id
    override fun component2(): Int? = type
    override fun component3(): Int? = status
    override fun component4(): String? = body
    override fun component5(): String? = subject
    override fun component6(): String? = recipient
    override fun component7(): LocalDateTime? = createdAt
    override fun component8(): LocalDateTime? = updatedAt
    override fun component9(): String? = templateType
    override fun component10(): ByteArray? = templateData
    override fun component11(): UUID? = nid
    override fun component12(): Int? = sendCount
    override fun value1(): UUID? = id
    override fun value2(): Int? = type
    override fun value3(): Int? = status
    override fun value4(): String? = body
    override fun value5(): String? = subject
    override fun value6(): String? = recipient
    override fun value7(): LocalDateTime? = createdAt
    override fun value8(): LocalDateTime? = updatedAt
    override fun value9(): String? = templateType
    override fun value10(): ByteArray? = templateData
    override fun value11(): UUID? = nid
    override fun value12(): Int? = sendCount

    override fun value1(value: UUID?): CourierMessagesRecord {
        this.id = value
        return this
    }

    override fun value2(value: Int?): CourierMessagesRecord {
        this.type = value
        return this
    }

    override fun value3(value: Int?): CourierMessagesRecord {
        this.status = value
        return this
    }

    override fun value4(value: String?): CourierMessagesRecord {
        this.body = value
        return this
    }

    override fun value5(value: String?): CourierMessagesRecord {
        this.subject = value
        return this
    }

    override fun value6(value: String?): CourierMessagesRecord {
        this.recipient = value
        return this
    }

    override fun value7(value: LocalDateTime?): CourierMessagesRecord {
        this.createdAt = value
        return this
    }

    override fun value8(value: LocalDateTime?): CourierMessagesRecord {
        this.updatedAt = value
        return this
    }

    override fun value9(value: String?): CourierMessagesRecord {
        this.templateType = value
        return this
    }

    override fun value10(value: ByteArray?): CourierMessagesRecord {
        this.templateData = value
        return this
    }

    override fun value11(value: UUID?): CourierMessagesRecord {
        this.nid = value
        return this
    }

    override fun value12(value: Int?): CourierMessagesRecord {
        this.sendCount = value
        return this
    }

    override fun values(value1: UUID?, value2: Int?, value3: Int?, value4: String?, value5: String?, value6: String?, value7: LocalDateTime?, value8: LocalDateTime?, value9: String?, value10: ByteArray?, value11: UUID?, value12: Int?): CourierMessagesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        return this
    }

    /**
     * Create a detached, initialised CourierMessagesRecord
     */
    constructor(id: UUID? = null, type: Int? = null, status: Int? = null, body: String? = null, subject: String? = null, recipient: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, templateType: String? = null, templateData: ByteArray? = null, nid: UUID? = null, sendCount: Int? = null): this() {
        this.id = id
        this.type = type
        this.status = status
        this.body = body
        this.subject = subject
        this.recipient = recipient
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.templateType = templateType
        this.templateData = templateData
        this.nid = nid
        this.sendCount = sendCount
    }

    /**
     * Create a detached, initialised CourierMessagesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.CourierMessages?): this() {
        if (value != null) {
            this.id = value.id
            this.type = value.type
            this.status = value.status
            this.body = value.body
            this.subject = value.subject
            this.recipient = value.recipient
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.templateType = value.templateType
            this.templateData = value.templateData
            this.nid = value.nid
            this.sendCount = value.sendCount
        }
    }
}
