/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.DailyChallenge

import java.time.LocalDate
import java.time.LocalDateTime

import org.jooq.JSON
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DailyChallengeRecord private constructor() : UpdatableRecordImpl<DailyChallengeRecord>(DailyChallenge.DAILY_CHALLENGE) {

    open var id: Int
        set(value): Unit = set(0, value)
        get(): Int = get(0) as Int

    open var uuid: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var createdAt: LocalDateTime
        set(value): Unit = set(2, value)
        get(): LocalDateTime = get(2) as LocalDateTime

    open var updatedAt: LocalDateTime
        set(value): Unit = set(3, value)
        get(): LocalDateTime = get(3) as LocalDateTime

    open var day: LocalDate
        set(value): Unit = set(4, value)
        get(): LocalDate = get(4) as LocalDate

    open var seed: Long
        set(value): Unit = set(5, value)
        get(): Long = get(5) as Long

    open var forcedDecks: JSON?
        set(value): Unit = set(6, value)
        get(): JSON? = get(6) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised DailyChallengeRecord
     */
    constructor(id: Int, uuid: String, createdAt: LocalDateTime, updatedAt: LocalDateTime, day: LocalDate, seed: Long, forcedDecks: JSON? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.day = day
        this.seed = seed
        this.forcedDecks = forcedDecks
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised DailyChallengeRecord
     */
    constructor(value: ch.yass.db.tables.pojos.DailyChallenge?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.day = value.day
            this.seed = value.seed
            this.forcedDecks = value.forcedDecks
            resetTouchedOnNotNull()
        }
    }
}
