/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Hand

import java.time.LocalDateTime

import org.jooq.JSON
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class HandRecord() : UpdatableRecordImpl<HandRecord>(Hand.HAND) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var gameId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var startingPlayerId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var trump: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var gschobe: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var north: JSON?
        set(value): Unit = set(8, value)
        get(): JSON? = get(8) as JSON?

    open var east: JSON?
        set(value): Unit = set(9, value)
        get(): JSON? = get(9) as JSON?

    open var south: JSON?
        set(value): Unit = set(10, value)
        get(): JSON? = get(10) as JSON?

    open var west: JSON?
        set(value): Unit = set(11, value)
        get(): JSON? = get(11) as JSON?

    open var northWeise: JSON?
        set(value): Unit = set(12, value)
        get(): JSON? = get(12) as JSON?

    open var eastWeise: JSON?
        set(value): Unit = set(13, value)
        get(): JSON? = get(13) as JSON?

    open var southWeise: JSON?
        set(value): Unit = set(14, value)
        get(): JSON? = get(14) as JSON?

    open var westWeise: JSON?
        set(value): Unit = set(15, value)
        get(): JSON? = get(15) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised HandRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, gameId: Int? = null, startingPlayerId: Int? = null, trump: String? = null, gschobe: String? = null, north: JSON? = null, east: JSON? = null, south: JSON? = null, west: JSON? = null, northWeise: JSON? = null, eastWeise: JSON? = null, southWeise: JSON? = null, westWeise: JSON? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.gameId = gameId
        this.startingPlayerId = startingPlayerId
        this.trump = trump
        this.gschobe = gschobe
        this.north = north
        this.east = east
        this.south = south
        this.west = west
        this.northWeise = northWeise
        this.eastWeise = eastWeise
        this.southWeise = southWeise
        this.westWeise = westWeise
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised HandRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Hand?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.gameId = value.gameId
            this.startingPlayerId = value.startingPlayerId
            this.trump = value.trump
            this.gschobe = value.gschobe
            this.north = value.north
            this.east = value.east
            this.south = value.south
            this.west = value.west
            this.northWeise = value.northWeise
            this.eastWeise = value.eastWeise
            this.southWeise = value.southWeise
            this.westWeise = value.westWeise
            resetChangedOnNotNull()
        }
    }
}
