/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityVerificationTokens

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityVerificationTokensRecord() : UpdatableRecordImpl<IdentityVerificationTokensRecord>(IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS), Record11<UUID?, String?, Boolean?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var token: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var used: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open var usedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var identityVerifiableAddressId: UUID?
        set(value): Unit = set(6, value)
        get(): UUID? = get(6) as UUID?

    open var selfserviceVerificationFlowId: UUID?
        set(value): Unit = set(7, value)
        get(): UUID? = get(7) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(10, value)
        get(): UUID? = get(10) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row11<UUID?, String?, Boolean?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.fieldsRow() as Row11<UUID?, String?, Boolean?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun valuesRow(): Row11<UUID?, String?, Boolean?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.valuesRow() as Row11<UUID?, String?, Boolean?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun field1(): Field<UUID?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.ID
    override fun field2(): Field<String?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.TOKEN
    override fun field3(): Field<Boolean?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.USED
    override fun field4(): Field<LocalDateTime?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.USED_AT
    override fun field5(): Field<LocalDateTime?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.EXPIRES_AT
    override fun field6(): Field<LocalDateTime?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.ISSUED_AT
    override fun field7(): Field<UUID?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.IDENTITY_VERIFIABLE_ADDRESS_ID
    override fun field8(): Field<UUID?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.SELFSERVICE_VERIFICATION_FLOW_ID
    override fun field9(): Field<LocalDateTime?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.CREATED_AT
    override fun field10(): Field<LocalDateTime?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.UPDATED_AT
    override fun field11(): Field<UUID?> = IdentityVerificationTokens.IDENTITY_VERIFICATION_TOKENS.NID
    override fun component1(): UUID? = id
    override fun component2(): String? = token
    override fun component3(): Boolean? = used
    override fun component4(): LocalDateTime? = usedAt
    override fun component5(): LocalDateTime? = expiresAt
    override fun component6(): LocalDateTime? = issuedAt
    override fun component7(): UUID? = identityVerifiableAddressId
    override fun component8(): UUID? = selfserviceVerificationFlowId
    override fun component9(): LocalDateTime? = createdAt
    override fun component10(): LocalDateTime? = updatedAt
    override fun component11(): UUID? = nid
    override fun value1(): UUID? = id
    override fun value2(): String? = token
    override fun value3(): Boolean? = used
    override fun value4(): LocalDateTime? = usedAt
    override fun value5(): LocalDateTime? = expiresAt
    override fun value6(): LocalDateTime? = issuedAt
    override fun value7(): UUID? = identityVerifiableAddressId
    override fun value8(): UUID? = selfserviceVerificationFlowId
    override fun value9(): LocalDateTime? = createdAt
    override fun value10(): LocalDateTime? = updatedAt
    override fun value11(): UUID? = nid

    override fun value1(value: UUID?): IdentityVerificationTokensRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityVerificationTokensRecord {
        this.token = value
        return this
    }

    override fun value3(value: Boolean?): IdentityVerificationTokensRecord {
        this.used = value
        return this
    }

    override fun value4(value: LocalDateTime?): IdentityVerificationTokensRecord {
        this.usedAt = value
        return this
    }

    override fun value5(value: LocalDateTime?): IdentityVerificationTokensRecord {
        this.expiresAt = value
        return this
    }

    override fun value6(value: LocalDateTime?): IdentityVerificationTokensRecord {
        this.issuedAt = value
        return this
    }

    override fun value7(value: UUID?): IdentityVerificationTokensRecord {
        this.identityVerifiableAddressId = value
        return this
    }

    override fun value8(value: UUID?): IdentityVerificationTokensRecord {
        this.selfserviceVerificationFlowId = value
        return this
    }

    override fun value9(value: LocalDateTime?): IdentityVerificationTokensRecord {
        this.createdAt = value
        return this
    }

    override fun value10(value: LocalDateTime?): IdentityVerificationTokensRecord {
        this.updatedAt = value
        return this
    }

    override fun value11(value: UUID?): IdentityVerificationTokensRecord {
        this.nid = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: Boolean?, value4: LocalDateTime?, value5: LocalDateTime?, value6: LocalDateTime?, value7: UUID?, value8: UUID?, value9: LocalDateTime?, value10: LocalDateTime?, value11: UUID?): IdentityVerificationTokensRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        return this
    }

    /**
     * Create a detached, initialised IdentityVerificationTokensRecord
     */
    constructor(id: UUID? = null, token: String? = null, used: Boolean? = null, usedAt: LocalDateTime? = null, expiresAt: LocalDateTime? = null, issuedAt: LocalDateTime? = null, identityVerifiableAddressId: UUID? = null, selfserviceVerificationFlowId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, nid: UUID? = null): this() {
        this.id = id
        this.token = token
        this.used = used
        this.usedAt = usedAt
        this.expiresAt = expiresAt
        this.issuedAt = issuedAt
        this.identityVerifiableAddressId = identityVerifiableAddressId
        this.selfserviceVerificationFlowId = selfserviceVerificationFlowId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.nid = nid
    }

    /**
     * Create a detached, initialised IdentityVerificationTokensRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityVerificationTokens?): this() {
        if (value != null) {
            this.id = value.id
            this.token = value.token
            this.used = value.used
            this.usedAt = value.usedAt
            this.expiresAt = value.expiresAt
            this.issuedAt = value.issuedAt
            this.identityVerifiableAddressId = value.identityVerifiableAddressId
            this.selfserviceVerificationFlowId = value.selfserviceVerificationFlowId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.nid = value.nid
        }
    }
}
