/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityVerificationCodes

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityVerificationCodesRecord() : UpdatableRecordImpl<IdentityVerificationCodesRecord>(IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES), Record10<UUID?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var codeHmac: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var usedAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var identityVerifiableAddressId: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var selfserviceVerificationFlowId: UUID?
        set(value): Unit = set(6, value)
        get(): UUID? = get(6) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(9, value)
        get(): UUID? = get(9) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<UUID?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.fieldsRow() as Row10<UUID?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun valuesRow(): Row10<UUID?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.valuesRow() as Row10<UUID?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun field1(): Field<UUID?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.ID
    override fun field2(): Field<String?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.CODE_HMAC
    override fun field3(): Field<LocalDateTime?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.USED_AT
    override fun field4(): Field<UUID?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.IDENTITY_VERIFIABLE_ADDRESS_ID
    override fun field5(): Field<LocalDateTime?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.EXPIRES_AT
    override fun field6(): Field<LocalDateTime?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.ISSUED_AT
    override fun field7(): Field<UUID?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.SELFSERVICE_VERIFICATION_FLOW_ID
    override fun field8(): Field<LocalDateTime?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.CREATED_AT
    override fun field9(): Field<LocalDateTime?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.UPDATED_AT
    override fun field10(): Field<UUID?> = IdentityVerificationCodes.IDENTITY_VERIFICATION_CODES.NID
    override fun component1(): UUID? = id
    override fun component2(): String? = codeHmac
    override fun component3(): LocalDateTime? = usedAt
    override fun component4(): UUID? = identityVerifiableAddressId
    override fun component5(): LocalDateTime? = expiresAt
    override fun component6(): LocalDateTime? = issuedAt
    override fun component7(): UUID? = selfserviceVerificationFlowId
    override fun component8(): LocalDateTime? = createdAt
    override fun component9(): LocalDateTime? = updatedAt
    override fun component10(): UUID? = nid
    override fun value1(): UUID? = id
    override fun value2(): String? = codeHmac
    override fun value3(): LocalDateTime? = usedAt
    override fun value4(): UUID? = identityVerifiableAddressId
    override fun value5(): LocalDateTime? = expiresAt
    override fun value6(): LocalDateTime? = issuedAt
    override fun value7(): UUID? = selfserviceVerificationFlowId
    override fun value8(): LocalDateTime? = createdAt
    override fun value9(): LocalDateTime? = updatedAt
    override fun value10(): UUID? = nid

    override fun value1(value: UUID?): IdentityVerificationCodesRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityVerificationCodesRecord {
        this.codeHmac = value
        return this
    }

    override fun value3(value: LocalDateTime?): IdentityVerificationCodesRecord {
        this.usedAt = value
        return this
    }

    override fun value4(value: UUID?): IdentityVerificationCodesRecord {
        this.identityVerifiableAddressId = value
        return this
    }

    override fun value5(value: LocalDateTime?): IdentityVerificationCodesRecord {
        this.expiresAt = value
        return this
    }

    override fun value6(value: LocalDateTime?): IdentityVerificationCodesRecord {
        this.issuedAt = value
        return this
    }

    override fun value7(value: UUID?): IdentityVerificationCodesRecord {
        this.selfserviceVerificationFlowId = value
        return this
    }

    override fun value8(value: LocalDateTime?): IdentityVerificationCodesRecord {
        this.createdAt = value
        return this
    }

    override fun value9(value: LocalDateTime?): IdentityVerificationCodesRecord {
        this.updatedAt = value
        return this
    }

    override fun value10(value: UUID?): IdentityVerificationCodesRecord {
        this.nid = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: LocalDateTime?, value4: UUID?, value5: LocalDateTime?, value6: LocalDateTime?, value7: UUID?, value8: LocalDateTime?, value9: LocalDateTime?, value10: UUID?): IdentityVerificationCodesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised IdentityVerificationCodesRecord
     */
    constructor(id: UUID? = null, codeHmac: String? = null, usedAt: LocalDateTime? = null, identityVerifiableAddressId: UUID? = null, expiresAt: LocalDateTime? = null, issuedAt: LocalDateTime? = null, selfserviceVerificationFlowId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, nid: UUID? = null): this() {
        this.id = id
        this.codeHmac = codeHmac
        this.usedAt = usedAt
        this.identityVerifiableAddressId = identityVerifiableAddressId
        this.expiresAt = expiresAt
        this.issuedAt = issuedAt
        this.selfserviceVerificationFlowId = selfserviceVerificationFlowId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.nid = nid
    }

    /**
     * Create a detached, initialised IdentityVerificationCodesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityVerificationCodes?): this() {
        if (value != null) {
            this.id = value.id
            this.codeHmac = value.codeHmac
            this.usedAt = value.usedAt
            this.identityVerifiableAddressId = value.identityVerifiableAddressId
            this.expiresAt = value.expiresAt
            this.issuedAt = value.issuedAt
            this.selfserviceVerificationFlowId = value.selfserviceVerificationFlowId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.nid = value.nid
        }
    }
}
