/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityVerifiableAddresses

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityVerifiableAddressesRecord() : UpdatableRecordImpl<IdentityVerifiableAddressesRecord>(IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES), Record10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var status: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var via: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var verified: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    open var value: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var verifiedAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var identityId: UUID?
        set(value): Unit = set(6, value)
        get(): UUID? = get(6) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(9, value)
        get(): UUID? = get(9) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.fieldsRow() as Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun valuesRow(): Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.valuesRow() as Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun field1(): Field<UUID?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.ID
    override fun field2(): Field<String?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.STATUS
    override fun field3(): Field<String?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VIA
    override fun field4(): Field<Boolean?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VERIFIED
    override fun field5(): Field<String?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VALUE
    override fun field6(): Field<LocalDateTime?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.VERIFIED_AT
    override fun field7(): Field<UUID?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.IDENTITY_ID
    override fun field8(): Field<LocalDateTime?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.CREATED_AT
    override fun field9(): Field<LocalDateTime?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.UPDATED_AT
    override fun field10(): Field<UUID?> = IdentityVerifiableAddresses.IDENTITY_VERIFIABLE_ADDRESSES.NID
    override fun component1(): UUID? = id
    override fun component2(): String? = status
    override fun component3(): String? = via
    override fun component4(): Boolean? = verified
    override fun component5(): String? = value
    override fun component6(): LocalDateTime? = verifiedAt
    override fun component7(): UUID? = identityId
    override fun component8(): LocalDateTime? = createdAt
    override fun component9(): LocalDateTime? = updatedAt
    override fun component10(): UUID? = nid
    override fun value1(): UUID? = id
    override fun value2(): String? = status
    override fun value3(): String? = via
    override fun value4(): Boolean? = verified
    override fun value5(): String? = value
    override fun value6(): LocalDateTime? = verifiedAt
    override fun value7(): UUID? = identityId
    override fun value8(): LocalDateTime? = createdAt
    override fun value9(): LocalDateTime? = updatedAt
    override fun value10(): UUID? = nid

    override fun value1(value: UUID?): IdentityVerifiableAddressesRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityVerifiableAddressesRecord {
        this.status = value
        return this
    }

    override fun value3(value: String?): IdentityVerifiableAddressesRecord {
        this.via = value
        return this
    }

    override fun value4(value: Boolean?): IdentityVerifiableAddressesRecord {
        this.verified = value
        return this
    }

    override fun value5(value: String?): IdentityVerifiableAddressesRecord {
        this.value = value
        return this
    }

    override fun value6(value: LocalDateTime?): IdentityVerifiableAddressesRecord {
        this.verifiedAt = value
        return this
    }

    override fun value7(value: UUID?): IdentityVerifiableAddressesRecord {
        this.identityId = value
        return this
    }

    override fun value8(value: LocalDateTime?): IdentityVerifiableAddressesRecord {
        this.createdAt = value
        return this
    }

    override fun value9(value: LocalDateTime?): IdentityVerifiableAddressesRecord {
        this.updatedAt = value
        return this
    }

    override fun value10(value: UUID?): IdentityVerifiableAddressesRecord {
        this.nid = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: String?, value4: Boolean?, value5: String?, value6: LocalDateTime?, value7: UUID?, value8: LocalDateTime?, value9: LocalDateTime?, value10: UUID?): IdentityVerifiableAddressesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised IdentityVerifiableAddressesRecord
     */
    constructor(id: UUID? = null, status: String? = null, via: String? = null, verified: Boolean? = null, value: String? = null, verifiedAt: LocalDateTime? = null, identityId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, nid: UUID? = null): this() {
        this.id = id
        this.status = status
        this.via = via
        this.verified = verified
        this.value = value
        this.verifiedAt = verifiedAt
        this.identityId = identityId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.nid = nid
    }

    /**
     * Create a detached, initialised IdentityVerifiableAddressesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityVerifiableAddresses?): this() {
        if (value != null) {
            this.id = value.id
            this.status = value.status
            this.via = value.via
            this.verified = value.verified
            this.value = value.value
            this.verifiedAt = value.verifiedAt
            this.identityId = value.identityId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.nid = value.nid
        }
    }
}
