/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Player

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerRecord() : UpdatableRecordImpl<PlayerRecord>(Player.PLAYER), Record8<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?, String?, String?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var name: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var bot: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var oryUuid: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var anonToken: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?, String?, String?> = super.fieldsRow() as Row8<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?, String?, String?>
    override fun valuesRow(): Row8<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?, String?, String?> = super.valuesRow() as Row8<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?, String?, String?>
    override fun field1(): Field<Int?> = Player.PLAYER.ID
    override fun field2(): Field<String?> = Player.PLAYER.UUID
    override fun field3(): Field<LocalDateTime?> = Player.PLAYER.CREATED_AT
    override fun field4(): Field<LocalDateTime?> = Player.PLAYER.UPDATED_AT
    override fun field5(): Field<String?> = Player.PLAYER.NAME
    override fun field6(): Field<Boolean?> = Player.PLAYER.BOT
    override fun field7(): Field<String?> = Player.PLAYER.ORY_UUID
    override fun field8(): Field<String?> = Player.PLAYER.ANON_TOKEN
    override fun component1(): Int? = id
    override fun component2(): String? = uuid
    override fun component3(): LocalDateTime? = createdAt
    override fun component4(): LocalDateTime? = updatedAt
    override fun component5(): String? = name
    override fun component6(): Boolean? = bot
    override fun component7(): String? = oryUuid
    override fun component8(): String? = anonToken
    override fun value1(): Int? = id
    override fun value2(): String? = uuid
    override fun value3(): LocalDateTime? = createdAt
    override fun value4(): LocalDateTime? = updatedAt
    override fun value5(): String? = name
    override fun value6(): Boolean? = bot
    override fun value7(): String? = oryUuid
    override fun value8(): String? = anonToken

    override fun value1(value: Int?): PlayerRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): PlayerRecord {
        this.uuid = value
        return this
    }

    override fun value3(value: LocalDateTime?): PlayerRecord {
        this.createdAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): PlayerRecord {
        this.updatedAt = value
        return this
    }

    override fun value5(value: String?): PlayerRecord {
        this.name = value
        return this
    }

    override fun value6(value: Boolean?): PlayerRecord {
        this.bot = value
        return this
    }

    override fun value7(value: String?): PlayerRecord {
        this.oryUuid = value
        return this
    }

    override fun value8(value: String?): PlayerRecord {
        this.anonToken = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: String?, value6: Boolean?, value7: String?, value8: String?): PlayerRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, name: String? = null, bot: Boolean? = null, oryUuid: String? = null, anonToken: String? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.name = name
        this.bot = bot
        this.oryUuid = oryUuid
        this.anonToken = anonToken
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Player?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.name = value.name
            this.bot = value.bot
            this.oryUuid = value.oryUuid
            this.anonToken = value.anonToken
        }
    }
}
