/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Player

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerRecord private constructor() : UpdatableRecordImpl<PlayerRecord>(Player.PLAYER) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var createdAt: LocalDateTime
        set(value): Unit = set(2, value)
        get(): LocalDateTime = get(2) as LocalDateTime

    open var updatedAt: LocalDateTime
        set(value): Unit = set(3, value)
        get(): LocalDateTime = get(3) as LocalDateTime

    open var name: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var bot: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var oryUuid: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var anonToken: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PlayerRecord
     */
    constructor(id: Int? = null, uuid: String, createdAt: LocalDateTime, updatedAt: LocalDateTime, name: String, bot: Boolean? = null, oryUuid: String? = null, anonToken: String? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.name = name
        this.bot = bot
        this.oryUuid = oryUuid
        this.anonToken = anonToken
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Player?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.name = value.name
            this.bot = value.bot
            this.oryUuid = value.oryUuid
            this.anonToken = value.anonToken
            resetChangedOnNotNull()
        }
    }
}
