/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Seat

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeatRecord() : UpdatableRecordImpl<SeatRecord>(Seat.SEAT) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var playerId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var gameId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var position: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var rejoinedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var playerPing: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var status: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised SeatRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, playerId: Int? = null, gameId: Int? = null, position: String? = null, rejoinedAt: LocalDateTime? = null, playerPing: LocalDateTime? = null, status: String? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.playerId = playerId
        this.gameId = gameId
        this.position = position
        this.rejoinedAt = rejoinedAt
        this.playerPing = playerPing
        this.status = status
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised SeatRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Seat?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.playerId = value.playerId
            this.gameId = value.gameId
            this.position = value.position
            this.rejoinedAt = value.rejoinedAt
            this.playerPing = value.playerPing
            this.status = value.status
            resetChangedOnNotNull()
        }
    }
}
