/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Seat

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeatRecord() : UpdatableRecordImpl<SeatRecord>(Seat.SEAT), Record8<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, LocalDateTime?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var playerId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var gameId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var position: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var rejoinedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, LocalDateTime?> = super.fieldsRow() as Row8<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, LocalDateTime?>
    override fun valuesRow(): Row8<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, LocalDateTime?> = super.valuesRow() as Row8<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, LocalDateTime?>
    override fun field1(): Field<Int?> = Seat.SEAT.ID
    override fun field2(): Field<String?> = Seat.SEAT.UUID
    override fun field3(): Field<LocalDateTime?> = Seat.SEAT.CREATED_AT
    override fun field4(): Field<LocalDateTime?> = Seat.SEAT.UPDATED_AT
    override fun field5(): Field<Int?> = Seat.SEAT.PLAYER_ID
    override fun field6(): Field<Int?> = Seat.SEAT.GAME_ID
    override fun field7(): Field<String?> = Seat.SEAT.POSITION
    override fun field8(): Field<LocalDateTime?> = Seat.SEAT.REJOINED_AT
    override fun component1(): Int? = id
    override fun component2(): String? = uuid
    override fun component3(): LocalDateTime? = createdAt
    override fun component4(): LocalDateTime? = updatedAt
    override fun component5(): Int? = playerId
    override fun component6(): Int? = gameId
    override fun component7(): String? = position
    override fun component8(): LocalDateTime? = rejoinedAt
    override fun value1(): Int? = id
    override fun value2(): String? = uuid
    override fun value3(): LocalDateTime? = createdAt
    override fun value4(): LocalDateTime? = updatedAt
    override fun value5(): Int? = playerId
    override fun value6(): Int? = gameId
    override fun value7(): String? = position
    override fun value8(): LocalDateTime? = rejoinedAt

    override fun value1(value: Int?): SeatRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SeatRecord {
        this.uuid = value
        return this
    }

    override fun value3(value: LocalDateTime?): SeatRecord {
        this.createdAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): SeatRecord {
        this.updatedAt = value
        return this
    }

    override fun value5(value: Int?): SeatRecord {
        this.playerId = value
        return this
    }

    override fun value6(value: Int?): SeatRecord {
        this.gameId = value
        return this
    }

    override fun value7(value: String?): SeatRecord {
        this.position = value
        return this
    }

    override fun value8(value: LocalDateTime?): SeatRecord {
        this.rejoinedAt = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: Int?, value6: Int?, value7: String?, value8: LocalDateTime?): SeatRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised SeatRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, playerId: Int? = null, gameId: Int? = null, position: String? = null, rejoinedAt: LocalDateTime? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.playerId = playerId
        this.gameId = gameId
        this.position = position
        this.rejoinedAt = rejoinedAt
    }

    /**
     * Create a detached, initialised SeatRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Seat?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.playerId = value.playerId
            this.gameId = value.gameId
            this.position = value.position
            this.rejoinedAt = value.rejoinedAt
        }
    }
}
