/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.SelfserviceRegistrationFlows

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SelfserviceRegistrationFlowsRecord() : UpdatableRecordImpl<SelfserviceRegistrationFlowsRecord>(SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS), Record13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var requestUrl: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var activeMethod: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var csrfToken: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var type: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var ui: JSONB?
        set(value): Unit = set(9, value)
        get(): JSONB? = get(9) as JSONB?

    open var nid: UUID?
        set(value): Unit = set(10, value)
        get(): UUID? = get(10) as UUID?

    open var internalContext: JSONB?
        set(value): Unit = set(11, value)
        get(): JSONB? = get(11) as JSONB?

    open var oauth2LoginChallenge: UUID?
        set(value): Unit = set(12, value)
        get(): UUID? = get(12) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?> = super.fieldsRow() as Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?>
    override fun valuesRow(): Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?> = super.valuesRow() as Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?>
    override fun field1(): Field<UUID?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.ID
    override fun field2(): Field<String?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.REQUEST_URL
    override fun field3(): Field<LocalDateTime?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.ISSUED_AT
    override fun field4(): Field<LocalDateTime?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.EXPIRES_AT
    override fun field5(): Field<String?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.ACTIVE_METHOD
    override fun field6(): Field<String?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.CSRF_TOKEN
    override fun field7(): Field<LocalDateTime?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.CREATED_AT
    override fun field8(): Field<LocalDateTime?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.UPDATED_AT
    override fun field9(): Field<String?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.TYPE
    override fun field10(): Field<JSONB?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.UI
    override fun field11(): Field<UUID?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.NID
    override fun field12(): Field<JSONB?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.INTERNAL_CONTEXT
    override fun field13(): Field<UUID?> = SelfserviceRegistrationFlows.SELFSERVICE_REGISTRATION_FLOWS.OAUTH2_LOGIN_CHALLENGE
    override fun component1(): UUID? = id
    override fun component2(): String? = requestUrl
    override fun component3(): LocalDateTime? = issuedAt
    override fun component4(): LocalDateTime? = expiresAt
    override fun component5(): String? = activeMethod
    override fun component6(): String? = csrfToken
    override fun component7(): LocalDateTime? = createdAt
    override fun component8(): LocalDateTime? = updatedAt
    override fun component9(): String? = type
    override fun component10(): JSONB? = ui
    override fun component11(): UUID? = nid
    override fun component12(): JSONB? = internalContext
    override fun component13(): UUID? = oauth2LoginChallenge
    override fun value1(): UUID? = id
    override fun value2(): String? = requestUrl
    override fun value3(): LocalDateTime? = issuedAt
    override fun value4(): LocalDateTime? = expiresAt
    override fun value5(): String? = activeMethod
    override fun value6(): String? = csrfToken
    override fun value7(): LocalDateTime? = createdAt
    override fun value8(): LocalDateTime? = updatedAt
    override fun value9(): String? = type
    override fun value10(): JSONB? = ui
    override fun value11(): UUID? = nid
    override fun value12(): JSONB? = internalContext
    override fun value13(): UUID? = oauth2LoginChallenge

    override fun value1(value: UUID?): SelfserviceRegistrationFlowsRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SelfserviceRegistrationFlowsRecord {
        this.requestUrl = value
        return this
    }

    override fun value3(value: LocalDateTime?): SelfserviceRegistrationFlowsRecord {
        this.issuedAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): SelfserviceRegistrationFlowsRecord {
        this.expiresAt = value
        return this
    }

    override fun value5(value: String?): SelfserviceRegistrationFlowsRecord {
        this.activeMethod = value
        return this
    }

    override fun value6(value: String?): SelfserviceRegistrationFlowsRecord {
        this.csrfToken = value
        return this
    }

    override fun value7(value: LocalDateTime?): SelfserviceRegistrationFlowsRecord {
        this.createdAt = value
        return this
    }

    override fun value8(value: LocalDateTime?): SelfserviceRegistrationFlowsRecord {
        this.updatedAt = value
        return this
    }

    override fun value9(value: String?): SelfserviceRegistrationFlowsRecord {
        this.type = value
        return this
    }

    override fun value10(value: JSONB?): SelfserviceRegistrationFlowsRecord {
        this.ui = value
        return this
    }

    override fun value11(value: UUID?): SelfserviceRegistrationFlowsRecord {
        this.nid = value
        return this
    }

    override fun value12(value: JSONB?): SelfserviceRegistrationFlowsRecord {
        this.internalContext = value
        return this
    }

    override fun value13(value: UUID?): SelfserviceRegistrationFlowsRecord {
        this.oauth2LoginChallenge = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: String?, value6: String?, value7: LocalDateTime?, value8: LocalDateTime?, value9: String?, value10: JSONB?, value11: UUID?, value12: JSONB?, value13: UUID?): SelfserviceRegistrationFlowsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised SelfserviceRegistrationFlowsRecord
     */
    constructor(id: UUID? = null, requestUrl: String? = null, issuedAt: LocalDateTime? = null, expiresAt: LocalDateTime? = null, activeMethod: String? = null, csrfToken: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, type: String? = null, ui: JSONB? = null, nid: UUID? = null, internalContext: JSONB? = null, oauth2LoginChallenge: UUID? = null): this() {
        this.id = id
        this.requestUrl = requestUrl
        this.issuedAt = issuedAt
        this.expiresAt = expiresAt
        this.activeMethod = activeMethod
        this.csrfToken = csrfToken
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.type = type
        this.ui = ui
        this.nid = nid
        this.internalContext = internalContext
        this.oauth2LoginChallenge = oauth2LoginChallenge
    }

    /**
     * Create a detached, initialised SelfserviceRegistrationFlowsRecord
     */
    constructor(value: ch.yass.db.tables.pojos.SelfserviceRegistrationFlows?): this() {
        if (value != null) {
            this.id = value.id
            this.requestUrl = value.requestUrl
            this.issuedAt = value.issuedAt
            this.expiresAt = value.expiresAt
            this.activeMethod = value.activeMethod
            this.csrfToken = value.csrfToken
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.type = value.type
            this.ui = value.ui
            this.nid = value.nid
            this.internalContext = value.internalContext
            this.oauth2LoginChallenge = value.oauth2LoginChallenge
        }
    }
}
