/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.SessionDevices

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SessionDevicesRecord() : UpdatableRecordImpl<SessionDevicesRecord>(SessionDevices.SESSION_DEVICES), Record8<UUID?, String?, String?, String?, UUID?, UUID?, LocalDateTime?, LocalDateTime?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var ipAddress: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var userAgent: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var location: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var nid: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var sessionId: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<UUID?, String?, String?, String?, UUID?, UUID?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row8<UUID?, String?, String?, String?, UUID?, UUID?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row8<UUID?, String?, String?, String?, UUID?, UUID?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row8<UUID?, String?, String?, String?, UUID?, UUID?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<UUID?> = SessionDevices.SESSION_DEVICES.ID
    override fun field2(): Field<String?> = SessionDevices.SESSION_DEVICES.IP_ADDRESS
    override fun field3(): Field<String?> = SessionDevices.SESSION_DEVICES.USER_AGENT
    override fun field4(): Field<String?> = SessionDevices.SESSION_DEVICES.LOCATION
    override fun field5(): Field<UUID?> = SessionDevices.SESSION_DEVICES.NID
    override fun field6(): Field<UUID?> = SessionDevices.SESSION_DEVICES.SESSION_ID
    override fun field7(): Field<LocalDateTime?> = SessionDevices.SESSION_DEVICES.CREATED_AT
    override fun field8(): Field<LocalDateTime?> = SessionDevices.SESSION_DEVICES.UPDATED_AT
    override fun component1(): UUID? = id
    override fun component2(): String? = ipAddress
    override fun component3(): String? = userAgent
    override fun component4(): String? = location
    override fun component5(): UUID? = nid
    override fun component6(): UUID? = sessionId
    override fun component7(): LocalDateTime? = createdAt
    override fun component8(): LocalDateTime? = updatedAt
    override fun value1(): UUID? = id
    override fun value2(): String? = ipAddress
    override fun value3(): String? = userAgent
    override fun value4(): String? = location
    override fun value5(): UUID? = nid
    override fun value6(): UUID? = sessionId
    override fun value7(): LocalDateTime? = createdAt
    override fun value8(): LocalDateTime? = updatedAt

    override fun value1(value: UUID?): SessionDevicesRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SessionDevicesRecord {
        this.ipAddress = value
        return this
    }

    override fun value3(value: String?): SessionDevicesRecord {
        this.userAgent = value
        return this
    }

    override fun value4(value: String?): SessionDevicesRecord {
        this.location = value
        return this
    }

    override fun value5(value: UUID?): SessionDevicesRecord {
        this.nid = value
        return this
    }

    override fun value6(value: UUID?): SessionDevicesRecord {
        this.sessionId = value
        return this
    }

    override fun value7(value: LocalDateTime?): SessionDevicesRecord {
        this.createdAt = value
        return this
    }

    override fun value8(value: LocalDateTime?): SessionDevicesRecord {
        this.updatedAt = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: String?, value4: String?, value5: UUID?, value6: UUID?, value7: LocalDateTime?, value8: LocalDateTime?): SessionDevicesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised SessionDevicesRecord
     */
    constructor(id: UUID? = null, ipAddress: String? = null, userAgent: String? = null, location: String? = null, nid: UUID? = null, sessionId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null): this() {
        this.id = id
        this.ipAddress = ipAddress
        this.userAgent = userAgent
        this.location = location
        this.nid = nid
        this.sessionId = sessionId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
    }

    /**
     * Create a detached, initialised SessionDevicesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.SessionDevices?): this() {
        if (value != null) {
            this.id = value.id
            this.ipAddress = value.ipAddress
            this.userAgent = value.userAgent
            this.location = value.location
            this.nid = value.nid
            this.sessionId = value.sessionId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
        }
    }
}
