/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Trick

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.JSON
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TrickRecord() : UpdatableRecordImpl<TrickRecord>(Trick.TRICK), Record9<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, JSON?, JSON?, JSON?, JSON?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var handId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var north: JSON?
        set(value): Unit = set(5, value)
        get(): JSON? = get(5) as JSON?

    open var east: JSON?
        set(value): Unit = set(6, value)
        get(): JSON? = get(6) as JSON?

    open var south: JSON?
        set(value): Unit = set(7, value)
        get(): JSON? = get(7) as JSON?

    open var west: JSON?
        set(value): Unit = set(8, value)
        get(): JSON? = get(8) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, JSON?, JSON?, JSON?, JSON?> = super.fieldsRow() as Row9<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, JSON?, JSON?, JSON?, JSON?>
    override fun valuesRow(): Row9<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, JSON?, JSON?, JSON?, JSON?> = super.valuesRow() as Row9<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, JSON?, JSON?, JSON?, JSON?>
    override fun field1(): Field<Int?> = Trick.TRICK.ID
    override fun field2(): Field<String?> = Trick.TRICK.UUID
    override fun field3(): Field<LocalDateTime?> = Trick.TRICK.CREATED_AT
    override fun field4(): Field<LocalDateTime?> = Trick.TRICK.UPDATED_AT
    override fun field5(): Field<Int?> = Trick.TRICK.HAND_ID
    override fun field6(): Field<JSON?> = Trick.TRICK.NORTH
    override fun field7(): Field<JSON?> = Trick.TRICK.EAST
    override fun field8(): Field<JSON?> = Trick.TRICK.SOUTH
    override fun field9(): Field<JSON?> = Trick.TRICK.WEST
    override fun component1(): Int? = id
    override fun component2(): String? = uuid
    override fun component3(): LocalDateTime? = createdAt
    override fun component4(): LocalDateTime? = updatedAt
    override fun component5(): Int? = handId
    override fun component6(): JSON? = north
    override fun component7(): JSON? = east
    override fun component8(): JSON? = south
    override fun component9(): JSON? = west
    override fun value1(): Int? = id
    override fun value2(): String? = uuid
    override fun value3(): LocalDateTime? = createdAt
    override fun value4(): LocalDateTime? = updatedAt
    override fun value5(): Int? = handId
    override fun value6(): JSON? = north
    override fun value7(): JSON? = east
    override fun value8(): JSON? = south
    override fun value9(): JSON? = west

    override fun value1(value: Int?): TrickRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TrickRecord {
        this.uuid = value
        return this
    }

    override fun value3(value: LocalDateTime?): TrickRecord {
        this.createdAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): TrickRecord {
        this.updatedAt = value
        return this
    }

    override fun value5(value: Int?): TrickRecord {
        this.handId = value
        return this
    }

    override fun value6(value: JSON?): TrickRecord {
        this.north = value
        return this
    }

    override fun value7(value: JSON?): TrickRecord {
        this.east = value
        return this
    }

    override fun value8(value: JSON?): TrickRecord {
        this.south = value
        return this
    }

    override fun value9(value: JSON?): TrickRecord {
        this.west = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: Int?, value6: JSON?, value7: JSON?, value8: JSON?, value9: JSON?): TrickRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, handId: Int? = null, north: JSON? = null, east: JSON? = null, south: JSON? = null, west: JSON? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.handId = handId
        this.north = north
        this.east = east
        this.south = south
        this.west = west
    }

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Trick?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.handId = value.handId
            this.north = value.north
            this.east = value.east
            this.south = value.south
            this.west = value.west
        }
    }
}
