/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Trick

import java.time.LocalDateTime

import org.jooq.JSON
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TrickRecord() : UpdatableRecordImpl<TrickRecord>(Trick.TRICK) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var handId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var north: JSON?
        set(value): Unit = set(5, value)
        get(): JSON? = get(5) as JSON?

    open var east: JSON?
        set(value): Unit = set(6, value)
        get(): JSON? = get(6) as JSON?

    open var south: JSON?
        set(value): Unit = set(7, value)
        get(): JSON? = get(7) as JSON?

    open var west: JSON?
        set(value): Unit = set(8, value)
        get(): JSON? = get(8) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, handId: Int? = null, north: JSON? = null, east: JSON? = null, south: JSON? = null, west: JSON? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.handId = handId
        this.north = north
        this.east = east
        this.south = south
        this.west = west
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Trick?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.handId = value.handId
            this.north = value.north
            this.east = value.east
            this.south = value.south
            this.west = value.west
            resetChangedOnNotNull()
        }
    }
}
