ALTER TABLE hand
    ADD north_weise json,
    ADD east_weise json,
    ADD south_weise json,
    ADD west_weise json,
    ADD north_stoeck boolean,
    ADD east_stoeck boolean,
    ADD south_stoeck boolean,
    ADD west_stoeck boolean;