ALTER TABLE game
    ALTER COLUMN uuid SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE hand
    ALTER COLUMN game_id SET NOT NULL;

ALTER TABLE seat
    ALTER COLUMN uuid SET NOT NULL,
    ALTER COLUMN player_id SET NOT NULL,
    ALTER COLUMN game_id SET NOT NULL;

ALTER TABLE trick
    ALTER COLUMN uuid SET NOT NULL,
    ALTER COLUMN hand_id SET NOT NULL;
