package ch.yass.game.dto

enum class Skin {
    DEFAULT,
    ABSTRACT_GOODLUCK01,
    NATURE_MOUNTAIN01,
    BETA_HELMETKING01,
    FESTIVE_HALLOWEEN01,
    SLANG_HOLZSTOCK01,
    BOT01,
    BOT02,
    BOT03,
}