/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.keys


import ch.yass.db.tables.FlywaySchemaHistory
import ch.yass.db.tables.Game
import ch.yass.db.tables.Hand
import ch.yass.db.tables.Player
import ch.yass.db.tables.Seat
import ch.yass.db.tables.Trick
import ch.yass.db.tables.records.FlywaySchemaHistoryRecord
import ch.yass.db.tables.records.GameRecord
import ch.yass.db.tables.records.HandRecord
import ch.yass.db.tables.records.PlayerRecord
import ch.yass.db.tables.records.SeatRecord
import ch.yass.db.tables.records.TrickRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val GAME_PKEY: UniqueKey<GameRecord> = Internal.createUniqueKey(Game.GAME, DSL.name("game_pkey"), arrayOf(Game.GAME.ID), true)
val HAND_PKEY: UniqueKey<HandRecord> = Internal.createUniqueKey(Hand.HAND, DSL.name("hand_pkey"), arrayOf(Hand.HAND.ID), true)
val PLAYER_PKEY: UniqueKey<PlayerRecord> = Internal.createUniqueKey(Player.PLAYER, DSL.name("player_pkey"), arrayOf(Player.PLAYER.ID), true)
val SEAT_PKEY: UniqueKey<SeatRecord> = Internal.createUniqueKey(Seat.SEAT, DSL.name("seat_pkey"), arrayOf(Seat.SEAT.ID), true)
val TRICK_PKEY: UniqueKey<TrickRecord> = Internal.createUniqueKey(Trick.TRICK, DSL.name("trick_pkey"), arrayOf(Trick.TRICK.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val HAND__FK_HAND_ON_GAME: ForeignKey<HandRecord, GameRecord> = Internal.createForeignKey(Hand.HAND, DSL.name("fk_hand_on_game"), arrayOf(Hand.HAND.GAME_ID), ch.yass.db.keys.GAME_PKEY, arrayOf(Game.GAME.ID), true)
val HAND__FK_HAND_ON_STARTING_PLAYER: ForeignKey<HandRecord, PlayerRecord> = Internal.createForeignKey(Hand.HAND, DSL.name("fk_hand_on_starting_player"), arrayOf(Hand.HAND.STARTING_PLAYER_ID), ch.yass.db.keys.PLAYER_PKEY, arrayOf(Player.PLAYER.ID), true)
val SEAT__FK_SEAT_ON_GAME: ForeignKey<SeatRecord, GameRecord> = Internal.createForeignKey(Seat.SEAT, DSL.name("fk_seat_on_game"), arrayOf(Seat.SEAT.GAME_ID), ch.yass.db.keys.GAME_PKEY, arrayOf(Game.GAME.ID), true)
val SEAT__FK_SEAT_ON_PLAYER: ForeignKey<SeatRecord, PlayerRecord> = Internal.createForeignKey(Seat.SEAT, DSL.name("fk_seat_on_player"), arrayOf(Seat.SEAT.PLAYER_ID), ch.yass.db.keys.PLAYER_PKEY, arrayOf(Player.PLAYER.ID), true)
val TRICK__FK_TRICK_ON_HAND: ForeignKey<TrickRecord, HandRecord> = Internal.createForeignKey(Trick.TRICK, DSL.name("fk_trick_on_hand"), arrayOf(Trick.TRICK.HAND_ID), ch.yass.db.keys.HAND_PKEY, arrayOf(Hand.HAND.ID), true)
val TRICK__FK_TRICK_ON_WINNER: ForeignKey<TrickRecord, PlayerRecord> = Internal.createForeignKey(Trick.TRICK, DSL.name("fk_trick_on_winner"), arrayOf(Trick.TRICK.WINNER_ID), ch.yass.db.keys.PLAYER_PKEY, arrayOf(Player.PLAYER.ID), true)
