CREATE TABLE game (
  id SERIAL PRIMARY KEY,
   uuid VARCHAR(37),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   code VARCHAR(255) NOT NULL
);

CREATE TABLE hand (
  id SERIAL PRIMARY KEY,
   uuid VARCHAR(37),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   game_id INTEGER,
   starting_player_id INTEGER,
   trump INTEGER,
   gschobe BOOLEAN NOT NULL,
   points INTEGER NOT NULL,
   north json NOT NULL,
   east json NOT NULL,
   south json NOT NULL,
   west json NOT NULL
);

CREATE TABLE player (
  id SERIAL PRIMARY KEY,
   uuid VARCHAR(37) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255) NOT NULL
);

CREATE TABLE seat (
   id SERIAL PRIMARY KEY,
   uuid VARCHAR(37),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   player_id INTEGER NOT NULL,
   game_id INTEGER NOT NULL,
   position INTEGER
);

CREATE TABLE trick (
  id SERIAL PRIMARY KEY,
   uuid VARCHAR(37),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   hand_id INTEGER,
   winner_id INTEGER,
   points INTEGER NOT NULL
);

ALTER TABLE trick ADD CONSTRAINT FK_TRICK_ON_HAND FOREIGN KEY (hand_id) REFERENCES hand (id);

ALTER TABLE trick ADD CONSTRAINT FK_TRICK_ON_WINNER FOREIGN KEY (winner_id) REFERENCES player (id);

ALTER TABLE seat ADD CONSTRAINT FK_SEAT_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE seat ADD CONSTRAINT FK_SEAT_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE hand ADD CONSTRAINT FK_HAND_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE hand ADD CONSTRAINT FK_HAND_ON_STARTING_PLAYER FOREIGN KEY (starting_player_id) REFERENCES player (id);