/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.COURIER_MESSAGES_ID_NID_IDX
import ch.yass.db.indexes.COURIER_MESSAGES_NID_CREATED_AT_ID_IDX
import ch.yass.db.indexes.COURIER_MESSAGES_NID_ID_IDX
import ch.yass.db.indexes.COURIER_MESSAGES_NID_RECIPIENT_CREATED_AT_ID_IDX
import ch.yass.db.indexes.COURIER_MESSAGES_NID_STATUS_CREATED_AT_ID_IDX
import ch.yass.db.indexes.COURIER_MESSAGES_STATUS_IDX
import ch.yass.db.keys.COURIER_MESSAGES_PKEY
import ch.yass.db.keys.COURIER_MESSAGES__COURIER_MESSAGES_NID_FK_IDX
import ch.yass.db.tables.records.CourierMessagesRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourierMessages(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CourierMessagesRecord>?,
    aliased: Table<CourierMessagesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CourierMessagesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.courier_messages</code>
         */
        val COURIER_MESSAGES: CourierMessages = CourierMessages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CourierMessagesRecord> = CourierMessagesRecord::class.java

    /**
     * The column <code>public.courier_messages.id</code>.
     */
    val ID: TableField<CourierMessagesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.type</code>.
     */
    val TYPE: TableField<CourierMessagesRecord, Int?> = createField(DSL.name("type"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.status</code>.
     */
    val STATUS: TableField<CourierMessagesRecord, Int?> = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.body</code>.
     */
    val BODY: TableField<CourierMessagesRecord, String?> = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.subject</code>.
     */
    val SUBJECT: TableField<CourierMessagesRecord, String?> = createField(DSL.name("subject"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.recipient</code>.
     */
    val RECIPIENT: TableField<CourierMessagesRecord, String?> = createField(DSL.name("recipient"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.created_at</code>.
     */
    val CREATED_AT: TableField<CourierMessagesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.updated_at</code>.
     */
    val UPDATED_AT: TableField<CourierMessagesRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.courier_messages.template_type</code>.
     */
    val TEMPLATE_TYPE: TableField<CourierMessagesRecord, String?> = createField(DSL.name("template_type"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field("''::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.courier_messages.template_data</code>.
     */
    val TEMPLATE_DATA: TableField<CourierMessagesRecord, ByteArray?> = createField(DSL.name("template_data"), SQLDataType.BLOB, this, "")

    /**
     * The column <code>public.courier_messages.nid</code>.
     */
    val NID: TableField<CourierMessagesRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.courier_messages.send_count</code>.
     */
    val SEND_COUNT: TableField<CourierMessagesRecord, Int?> = createField(DSL.name("send_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<CourierMessagesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CourierMessagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.courier_messages</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.courier_messages</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.courier_messages</code> table reference
     */
    constructor(): this(DSL.name("courier_messages"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CourierMessagesRecord>): this(Internal.createPathAlias(child, key), child, key, COURIER_MESSAGES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(COURIER_MESSAGES_ID_NID_IDX, COURIER_MESSAGES_NID_CREATED_AT_ID_IDX, COURIER_MESSAGES_NID_ID_IDX, COURIER_MESSAGES_NID_RECIPIENT_CREATED_AT_ID_IDX, COURIER_MESSAGES_NID_STATUS_CREATED_AT_ID_IDX, COURIER_MESSAGES_STATUS_IDX)
    override fun getPrimaryKey(): UniqueKey<CourierMessagesRecord> = COURIER_MESSAGES_PKEY
    override fun getReferences(): List<ForeignKey<CourierMessagesRecord, *>> = listOf(COURIER_MESSAGES__COURIER_MESSAGES_NID_FK_IDX)

    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, COURIER_MESSAGES__COURIER_MESSAGES_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): CourierMessages = CourierMessages(DSL.name(alias), this)
    override fun `as`(alias: Name): CourierMessages = CourierMessages(alias, this)
    override fun `as`(alias: Table<*>): CourierMessages = CourierMessages(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CourierMessages = CourierMessages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CourierMessages = CourierMessages(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CourierMessages = CourierMessages(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?> = super.fieldsRow() as Row12<UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, Int?, Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, String?, ByteArray?, UUID?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
