/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.COURIER_MESSAGE_DISPATCHES_ID_MESSAGE_ID_NID_IDX
import ch.yass.db.keys.COURIER_MESSAGE_DISPATCHES_PKEY
import ch.yass.db.keys.COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_MESSAGE_ID_FK
import ch.yass.db.keys.COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_NID_FK
import ch.yass.db.tables.records.CourierMessageDispatchesRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSON
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourierMessageDispatches(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CourierMessageDispatchesRecord>?,
    aliased: Table<CourierMessageDispatchesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CourierMessageDispatchesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.courier_message_dispatches</code>
         */
        val COURIER_MESSAGE_DISPATCHES: CourierMessageDispatches = CourierMessageDispatches()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CourierMessageDispatchesRecord> = CourierMessageDispatchesRecord::class.java

    /**
     * The column <code>public.courier_message_dispatches.id</code>.
     */
    val ID: TableField<CourierMessageDispatchesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.courier_message_dispatches.message_id</code>.
     */
    val MESSAGE_ID: TableField<CourierMessageDispatchesRecord, UUID?> = createField(DSL.name("message_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.courier_message_dispatches.status</code>.
     */
    val STATUS: TableField<CourierMessageDispatchesRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(7).nullable(false), this, "")

    /**
     * The column <code>public.courier_message_dispatches.error</code>.
     */
    val ERROR: TableField<CourierMessageDispatchesRecord, JSON?> = createField(DSL.name("error"), SQLDataType.JSON, this, "")

    /**
     * The column <code>public.courier_message_dispatches.nid</code>.
     */
    val NID: TableField<CourierMessageDispatchesRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.courier_message_dispatches.created_at</code>.
     */
    val CREATED_AT: TableField<CourierMessageDispatchesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.courier_message_dispatches.updated_at</code>.
     */
    val UPDATED_AT: TableField<CourierMessageDispatchesRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<CourierMessageDispatchesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CourierMessageDispatchesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.courier_message_dispatches</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.courier_message_dispatches</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.courier_message_dispatches</code> table reference
     */
    constructor(): this(DSL.name("courier_message_dispatches"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CourierMessageDispatchesRecord>): this(Internal.createPathAlias(child, key), child, key, COURIER_MESSAGE_DISPATCHES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(COURIER_MESSAGE_DISPATCHES_ID_MESSAGE_ID_NID_IDX)
    override fun getPrimaryKey(): UniqueKey<CourierMessageDispatchesRecord> = COURIER_MESSAGE_DISPATCHES_PKEY
    override fun getReferences(): List<ForeignKey<CourierMessageDispatchesRecord, *>> = listOf(COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_MESSAGE_ID_FK, COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_NID_FK)

    private lateinit var _courierMessages: CourierMessages
    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.courier_messages</code>
     * table.
     */
    fun courierMessages(): CourierMessages {
        if (!this::_courierMessages.isInitialized)
            _courierMessages = CourierMessages(this, COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_MESSAGE_ID_FK)

        return _courierMessages;
    }

    val courierMessages: CourierMessages
        get(): CourierMessages = courierMessages()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, COURIER_MESSAGE_DISPATCHES__COURIER_MESSAGE_DISPATCHES_NID_FK)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): CourierMessageDispatches = CourierMessageDispatches(DSL.name(alias), this)
    override fun `as`(alias: Name): CourierMessageDispatches = CourierMessageDispatches(alias, this)
    override fun `as`(alias: Table<*>): CourierMessageDispatches = CourierMessageDispatches(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CourierMessageDispatches = CourierMessageDispatches(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CourierMessageDispatches = CourierMessageDispatches(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CourierMessageDispatches = CourierMessageDispatches(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, UUID?, String?, JSON?, UUID?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
