/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.DAILY_CHALLENGE_DAY_KEY
import ch.yass.db.keys.DAILY_CHALLENGE_PKEY
import ch.yass.db.tables.records.DailyChallengeRecord

import java.time.LocalDate
import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSON
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DailyChallenge(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DailyChallengeRecord>?,
    parentPath: InverseForeignKey<out Record, DailyChallengeRecord>?,
    aliased: Table<DailyChallengeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DailyChallengeRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.daily_challenge</code>
         */
        val DAILY_CHALLENGE: DailyChallenge = DailyChallenge()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DailyChallengeRecord> = DailyChallengeRecord::class.java

    /**
     * The column <code>public.daily_challenge.id</code>.
     */
    val ID: TableField<DailyChallengeRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.uuid</code>.
     */
    val UUID: TableField<DailyChallengeRecord, String?> = createField(DSL.name("uuid"), SQLDataType.VARCHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.created_at</code>.
     */
    val CREATED_AT: TableField<DailyChallengeRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.updated_at</code>.
     */
    val UPDATED_AT: TableField<DailyChallengeRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.day</code>.
     */
    val DAY: TableField<DailyChallengeRecord, LocalDate?> = createField(DSL.name("day"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.seed</code>.
     */
    val SEED: TableField<DailyChallengeRecord, Long?> = createField(DSL.name("seed"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.daily_challenge.forced_decks</code>.
     */
    val FORCED_DECKS: TableField<DailyChallengeRecord, JSON?> = createField(DSL.name("forced_decks"), SQLDataType.JSON.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::json"), SQLDataType.JSON)), this, "")

    private constructor(alias: Name, aliased: Table<DailyChallengeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DailyChallengeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DailyChallengeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.daily_challenge</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.daily_challenge</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.daily_challenge</code> table reference
     */
    constructor(): this(DSL.name("daily_challenge"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<DailyChallengeRecord> = DAILY_CHALLENGE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<DailyChallengeRecord>> = listOf(DAILY_CHALLENGE_DAY_KEY)
    override fun `as`(alias: String): DailyChallenge = DailyChallenge(DSL.name(alias), this)
    override fun `as`(alias: Name): DailyChallenge = DailyChallenge(alias, this)
    override fun `as`(alias: Table<*>): DailyChallenge = DailyChallenge(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DailyChallenge = DailyChallenge(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DailyChallenge = DailyChallenge(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DailyChallenge = DailyChallenge(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DailyChallenge = DailyChallenge(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DailyChallenge = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DailyChallenge = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DailyChallenge = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DailyChallenge = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DailyChallenge = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DailyChallenge = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DailyChallenge = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): DailyChallenge = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): DailyChallenge = where(DSL.notExists(select))
}
