/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.HAND_PKEY
import ch.yass.db.keys.HAND__FK_HAND_ON_GAME
import ch.yass.db.keys.HAND__FK_HAND_ON_STARTING_PLAYER
import ch.yass.db.tables.records.HandRecord

import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.JSON
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Hand(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, HandRecord>?,
    aliased: Table<HandRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<HandRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.hand</code>
         */
        val HAND: Hand = Hand()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<HandRecord> = HandRecord::class.java

    /**
     * The column <code>public.hand.id</code>.
     */
    val ID: TableField<HandRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.hand.uuid</code>.
     */
    val UUID: TableField<HandRecord, String?> = createField(DSL.name("uuid"), SQLDataType.VARCHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.hand.created_at</code>.
     */
    val CREATED_AT: TableField<HandRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.hand.updated_at</code>.
     */
    val UPDATED_AT: TableField<HandRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.hand.game_id</code>.
     */
    val GAME_ID: TableField<HandRecord, Int?> = createField(DSL.name("game_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.hand.starting_player_id</code>.
     */
    val STARTING_PLAYER_ID: TableField<HandRecord, Int?> = createField(DSL.name("starting_player_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.hand.trump</code>.
     */
    val TRUMP: TableField<HandRecord, String?> = createField(DSL.name("trump"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.hand.gschobe</code>.
     */
    val GSCHOBE: TableField<HandRecord, String?> = createField(DSL.name("gschobe"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>public.hand.north</code>.
     */
    val NORTH: TableField<HandRecord, JSON?> = createField(DSL.name("north"), SQLDataType.JSON.nullable(false), this, "")

    /**
     * The column <code>public.hand.east</code>.
     */
    val EAST: TableField<HandRecord, JSON?> = createField(DSL.name("east"), SQLDataType.JSON.nullable(false), this, "")

    /**
     * The column <code>public.hand.south</code>.
     */
    val SOUTH: TableField<HandRecord, JSON?> = createField(DSL.name("south"), SQLDataType.JSON.nullable(false), this, "")

    /**
     * The column <code>public.hand.west</code>.
     */
    val WEST: TableField<HandRecord, JSON?> = createField(DSL.name("west"), SQLDataType.JSON.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<HandRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<HandRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.hand</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.hand</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.hand</code> table reference
     */
    constructor(): this(DSL.name("hand"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, HandRecord>): this(Internal.createPathAlias(child, key), child, key, HAND, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<HandRecord, Int?> = super.getIdentity() as Identity<HandRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<HandRecord> = HAND_PKEY
    override fun getReferences(): List<ForeignKey<HandRecord, *>> = listOf(HAND__FK_HAND_ON_GAME, HAND__FK_HAND_ON_STARTING_PLAYER)

    private lateinit var _game: Game
    private lateinit var _player: Player

    /**
     * Get the implicit join path to the <code>public.game</code> table.
     */
    fun game(): Game {
        if (!this::_game.isInitialized)
            _game = Game(this, HAND__FK_HAND_ON_GAME)

        return _game;
    }

    val game: Game
        get(): Game = game()

    /**
     * Get the implicit join path to the <code>public.player</code> table.
     */
    fun player(): Player {
        if (!this::_player.isInitialized)
            _player = Player(this, HAND__FK_HAND_ON_STARTING_PLAYER)

        return _player;
    }

    val player: Player
        get(): Player = player()
    override fun `as`(alias: String): Hand = Hand(DSL.name(alias), this)
    override fun `as`(alias: Name): Hand = Hand(alias, this)
    override fun `as`(alias: Table<*>): Hand = Hand(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Hand = Hand(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Hand = Hand(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Hand = Hand(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, String?, JSON?, JSON?, JSON?, JSON?> = super.fieldsRow() as Row12<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, String?, JSON?, JSON?, JSON?, JSON?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, String?, JSON?, JSON?, JSON?, JSON?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?, String?, JSON?, JSON?, JSON?, JSON?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
