/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.IDENTITY_RECOVERY_CODES_IDENTITY_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_CODES_IDENTITY_RECOVERY_ADDRESS_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_CODES_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_CODES_NID_FLOW_ID_IDX
import ch.yass.db.keys.IDENTITY_RECOVERY_CODES_PKEY
import ch.yass.db.keys.IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_ID_FK
import ch.yass.db.keys.IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_RECOVERY_ADDRESSES_ID_FK
import ch.yass.db.keys.IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_NETWORKS_ID_FK
import ch.yass.db.keys.IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_SELFSERVICE_RECOVERY_FLOWS_ID_FK
import ch.yass.db.tables.records.IdentityRecoveryCodesRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityRecoveryCodes(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, IdentityRecoveryCodesRecord>?,
    aliased: Table<IdentityRecoveryCodesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<IdentityRecoveryCodesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.identity_recovery_codes</code>
         */
        val IDENTITY_RECOVERY_CODES: IdentityRecoveryCodes = IdentityRecoveryCodes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<IdentityRecoveryCodesRecord> = IdentityRecoveryCodesRecord::class.java

    /**
     * The column <code>public.identity_recovery_codes.id</code>.
     */
    val ID: TableField<IdentityRecoveryCodesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.code</code>.
     */
    val CODE: TableField<IdentityRecoveryCodesRecord, String?> = createField(DSL.name("code"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.used_at</code>.
     */
    val USED_AT: TableField<IdentityRecoveryCodesRecord, LocalDateTime?> = createField(DSL.name("used_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column
     * <code>public.identity_recovery_codes.identity_recovery_address_id</code>.
     */
    val IDENTITY_RECOVERY_ADDRESS_ID: TableField<IdentityRecoveryCodesRecord, UUID?> = createField(DSL.name("identity_recovery_address_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.identity_recovery_codes.code_type</code>.
     */
    val CODE_TYPE: TableField<IdentityRecoveryCodesRecord, Int?> = createField(DSL.name("code_type"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.expires_at</code>.
     */
    val EXPIRES_AT: TableField<IdentityRecoveryCodesRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2000-01-01 00:00:00'::timestamp without time zone", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.identity_recovery_codes.issued_at</code>.
     */
    val ISSUED_AT: TableField<IdentityRecoveryCodesRecord, LocalDateTime?> = createField(DSL.name("issued_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2000-01-01 00:00:00'::timestamp without time zone", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column
     * <code>public.identity_recovery_codes.selfservice_recovery_flow_id</code>.
     */
    val SELFSERVICE_RECOVERY_FLOW_ID: TableField<IdentityRecoveryCodesRecord, UUID?> = createField(DSL.name("selfservice_recovery_flow_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.created_at</code>.
     */
    val CREATED_AT: TableField<IdentityRecoveryCodesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.updated_at</code>.
     */
    val UPDATED_AT: TableField<IdentityRecoveryCodesRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.nid</code>.
     */
    val NID: TableField<IdentityRecoveryCodesRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_codes.identity_id</code>.
     */
    val IDENTITY_ID: TableField<IdentityRecoveryCodesRecord, UUID?> = createField(DSL.name("identity_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<IdentityRecoveryCodesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<IdentityRecoveryCodesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.identity_recovery_codes</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.identity_recovery_codes</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.identity_recovery_codes</code> table reference
     */
    constructor(): this(DSL.name("identity_recovery_codes"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, IdentityRecoveryCodesRecord>): this(Internal.createPathAlias(child, key), child, key, IDENTITY_RECOVERY_CODES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDENTITY_RECOVERY_CODES_ID_NID_IDX, IDENTITY_RECOVERY_CODES_IDENTITY_ID_NID_IDX, IDENTITY_RECOVERY_CODES_IDENTITY_RECOVERY_ADDRESS_ID_NID_IDX, IDENTITY_RECOVERY_CODES_NID_FLOW_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<IdentityRecoveryCodesRecord> = IDENTITY_RECOVERY_CODES_PKEY
    override fun getReferences(): List<ForeignKey<IdentityRecoveryCodesRecord, *>> = listOf(IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_RECOVERY_ADDRESSES_ID_FK, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_SELFSERVICE_RECOVERY_FLOWS_ID_FK, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_NETWORKS_ID_FK, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_ID_FK)

    private lateinit var _identityRecoveryAddresses: IdentityRecoveryAddresses
    private lateinit var _selfserviceRecoveryFlows: SelfserviceRecoveryFlows
    private lateinit var _networks: Networks
    private lateinit var _identities: Identities

    /**
     * Get the implicit join path to the
     * <code>public.identity_recovery_addresses</code> table.
     */
    fun identityRecoveryAddresses(): IdentityRecoveryAddresses {
        if (!this::_identityRecoveryAddresses.isInitialized)
            _identityRecoveryAddresses = IdentityRecoveryAddresses(this, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_RECOVERY_ADDRESSES_ID_FK)

        return _identityRecoveryAddresses;
    }

    val identityRecoveryAddresses: IdentityRecoveryAddresses
        get(): IdentityRecoveryAddresses = identityRecoveryAddresses()

    /**
     * Get the implicit join path to the
     * <code>public.selfservice_recovery_flows</code> table.
     */
    fun selfserviceRecoveryFlows(): SelfserviceRecoveryFlows {
        if (!this::_selfserviceRecoveryFlows.isInitialized)
            _selfserviceRecoveryFlows = SelfserviceRecoveryFlows(this, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_SELFSERVICE_RECOVERY_FLOWS_ID_FK)

        return _selfserviceRecoveryFlows;
    }

    val selfserviceRecoveryFlows: SelfserviceRecoveryFlows
        get(): SelfserviceRecoveryFlows = selfserviceRecoveryFlows()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_NETWORKS_ID_FK)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()

    /**
     * Get the implicit join path to the <code>public.identities</code> table.
     */
    fun identities(): Identities {
        if (!this::_identities.isInitialized)
            _identities = Identities(this, IDENTITY_RECOVERY_CODES__IDENTITY_RECOVERY_CODES_IDENTITY_ID_FK)

        return _identities;
    }

    val identities: Identities
        get(): Identities = identities()
    override fun `as`(alias: String): IdentityRecoveryCodes = IdentityRecoveryCodes(DSL.name(alias), this)
    override fun `as`(alias: Name): IdentityRecoveryCodes = IdentityRecoveryCodes(alias, this)
    override fun `as`(alias: Table<*>): IdentityRecoveryCodes = IdentityRecoveryCodes(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IdentityRecoveryCodes = IdentityRecoveryCodes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IdentityRecoveryCodes = IdentityRecoveryCodes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IdentityRecoveryCodes = IdentityRecoveryCodes(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<UUID?, String?, LocalDateTime?, UUID?, Int?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?> = super.fieldsRow() as Row12<UUID?, String?, LocalDateTime?, UUID?, Int?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, LocalDateTime?, UUID?, Int?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, LocalDateTime?, UUID?, Int?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
