/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTIFIER_NID_TYPE_UQ_IDX
import ch.yass.db.indexes.IDENTITY_CREDENTIAL_IDENTIFIERS_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_CREDENTIAL_IDENTIFIERS_NID_IDENTITY_CREDENTIAL_ID_IDX
import ch.yass.db.indexes.IDENTITY_CREDENTIAL_IDENTIFIERS_NID_ID_IDX
import ch.yass.db.keys.IDENTITY_CREDENTIAL_IDENTIFIERS_PKEY
import ch.yass.db.keys.IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTITY_CREDENTIAL_ID_FKEY
import ch.yass.db.keys.IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_NID_FK_IDX
import ch.yass.db.keys.IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_TYPE_ID_FK_IDX
import ch.yass.db.tables.records.IdentityCredentialIdentifiersRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityCredentialIdentifiers(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, IdentityCredentialIdentifiersRecord>?,
    aliased: Table<IdentityCredentialIdentifiersRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<IdentityCredentialIdentifiersRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.identity_credential_identifiers</code>
         */
        val IDENTITY_CREDENTIAL_IDENTIFIERS: IdentityCredentialIdentifiers = IdentityCredentialIdentifiers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<IdentityCredentialIdentifiersRecord> = IdentityCredentialIdentifiersRecord::class.java

    /**
     * The column <code>public.identity_credential_identifiers.id</code>.
     */
    val ID: TableField<IdentityCredentialIdentifiersRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>public.identity_credential_identifiers.identifier</code>.
     */
    val IDENTIFIER: TableField<IdentityCredentialIdentifiersRecord, String?> = createField(DSL.name("identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column
     * <code>public.identity_credential_identifiers.identity_credential_id</code>.
     */
    val IDENTITY_CREDENTIAL_ID: TableField<IdentityCredentialIdentifiersRecord, UUID?> = createField(DSL.name("identity_credential_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>public.identity_credential_identifiers.created_at</code>.
     */
    val CREATED_AT: TableField<IdentityCredentialIdentifiersRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column
     * <code>public.identity_credential_identifiers.updated_at</code>.
     */
    val UPDATED_AT: TableField<IdentityCredentialIdentifiersRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_credential_identifiers.nid</code>.
     */
    val NID: TableField<IdentityCredentialIdentifiersRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>public.identity_credential_identifiers.identity_credential_type_id</code>.
     */
    val IDENTITY_CREDENTIAL_TYPE_ID: TableField<IdentityCredentialIdentifiersRecord, UUID?> = createField(DSL.name("identity_credential_type_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<IdentityCredentialIdentifiersRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<IdentityCredentialIdentifiersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.identity_credential_identifiers</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.identity_credential_identifiers</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.identity_credential_identifiers</code> table
     * reference
     */
    constructor(): this(DSL.name("identity_credential_identifiers"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, IdentityCredentialIdentifiersRecord>): this(Internal.createPathAlias(child, key), child, key, IDENTITY_CREDENTIAL_IDENTIFIERS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDENTITY_CREDENTIAL_IDENTIFIERS_ID_NID_IDX, IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTIFIER_NID_TYPE_UQ_IDX, IDENTITY_CREDENTIAL_IDENTIFIERS_NID_ID_IDX, IDENTITY_CREDENTIAL_IDENTIFIERS_NID_IDENTITY_CREDENTIAL_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<IdentityCredentialIdentifiersRecord> = IDENTITY_CREDENTIAL_IDENTIFIERS_PKEY
    override fun getReferences(): List<ForeignKey<IdentityCredentialIdentifiersRecord, *>> = listOf(IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTITY_CREDENTIAL_ID_FKEY, IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_NID_FK_IDX, IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_TYPE_ID_FK_IDX)

    private lateinit var _identityCredentials: IdentityCredentials
    private lateinit var _networks: Networks
    private lateinit var _identityCredentialTypes: IdentityCredentialTypes

    /**
     * Get the implicit join path to the
     * <code>public.identity_credentials</code> table.
     */
    fun identityCredentials(): IdentityCredentials {
        if (!this::_identityCredentials.isInitialized)
            _identityCredentials = IdentityCredentials(this, IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_IDENTITY_CREDENTIAL_ID_FKEY)

        return _identityCredentials;
    }

    val identityCredentials: IdentityCredentials
        get(): IdentityCredentials = identityCredentials()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()

    /**
     * Get the implicit join path to the
     * <code>public.identity_credential_types</code> table.
     */
    fun identityCredentialTypes(): IdentityCredentialTypes {
        if (!this::_identityCredentialTypes.isInitialized)
            _identityCredentialTypes = IdentityCredentialTypes(this, IDENTITY_CREDENTIAL_IDENTIFIERS__IDENTITY_CREDENTIAL_IDENTIFIERS_TYPE_ID_FK_IDX)

        return _identityCredentialTypes;
    }

    val identityCredentialTypes: IdentityCredentialTypes
        get(): IdentityCredentialTypes = identityCredentialTypes()
    override fun `as`(alias: String): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(DSL.name(alias), this)
    override fun `as`(alias: Name): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(alias, this)
    override fun `as`(alias: Table<*>): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IdentityCredentialIdentifiers = IdentityCredentialIdentifiers(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?> = super.fieldsRow() as Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
