/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.MESSAGE_PKEY
import ch.yass.db.tables.records.MessageRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.JSON
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Message(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MessageRecord>?,
    parentPath: InverseForeignKey<out Record, MessageRecord>?,
    aliased: Table<MessageRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MessageRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.message</code>
         */
        val MESSAGE: Message = Message()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MessageRecord> = MessageRecord::class.java

    /**
     * The column <code>public.message.id</code>.
     */
    val ID: TableField<MessageRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.message.message</code>.
     */
    val MESSAGE_: TableField<MessageRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.message.meta</code>.
     */
    val META: TableField<MessageRecord, JSON?> = createField(DSL.name("meta"), SQLDataType.JSON.nullable(false), this, "")

    /**
     * The column <code>public.message.created_at</code>.
     */
    val CREATED_AT: TableField<MessageRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.message.updated_at</code>.
     */
    val UPDATED_AT: TableField<MessageRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<MessageRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MessageRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MessageRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.message</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.message</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.message</code> table reference
     */
    constructor(): this(DSL.name("message"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<MessageRecord, Int?> = super.getIdentity() as Identity<MessageRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<MessageRecord> = MESSAGE_PKEY
    override fun `as`(alias: String): Message = Message(DSL.name(alias), this)
    override fun `as`(alias: Name): Message = Message(alias, this)
    override fun `as`(alias: Table<*>): Message = Message(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Message = Message(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Message = Message(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Message = Message(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Message = Message(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Message = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Message = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Message = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Message = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Message = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Message = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Message = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Message = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Message = where(DSL.notExists(select))
}
