/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.NETWORKS_PKEY
import ch.yass.db.tables.records.NetworksRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Networks(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, NetworksRecord>?,
    aliased: Table<NetworksRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<NetworksRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.networks</code>
         */
        val NETWORKS: Networks = Networks()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<NetworksRecord> = NetworksRecord::class.java

    /**
     * The column <code>public.networks.id</code>.
     */
    val ID: TableField<NetworksRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.networks.created_at</code>.
     */
    val CREATED_AT: TableField<NetworksRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.networks.updated_at</code>.
     */
    val UPDATED_AT: TableField<NetworksRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<NetworksRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<NetworksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.networks</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.networks</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.networks</code> table reference
     */
    constructor(): this(DSL.name("networks"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, NetworksRecord>): this(Internal.createPathAlias(child, key), child, key, NETWORKS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<NetworksRecord> = NETWORKS_PKEY
    override fun `as`(alias: String): Networks = Networks(DSL.name(alias), this)
    override fun `as`(alias: Name): Networks = Networks(alias, this)
    override fun `as`(alias: Table<*>): Networks = Networks(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Networks = Networks(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Networks = Networks(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Networks = Networks(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<UUID?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row3<UUID?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
