/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.SELFSERVICE_SETTINGS_FLOWS_IDENTITY_ID_NID_IDX
import ch.yass.db.indexes.SELFSERVICE_SETTINGS_FLOWS_ID_NID_IDX
import ch.yass.db.indexes.SELFSERVICE_SETTINGS_FLOWS_NID_ID_IDX
import ch.yass.db.keys.SELFSERVICE_PROFILE_MANAGEMENT_REQUESTS_PKEY
import ch.yass.db.keys.SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_PROFILE_MANAGEMENT_REQUESTS_IDENTITY_ID_FKEY
import ch.yass.db.keys.SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_SETTINGS_FLOWS_NID_FK_IDX
import ch.yass.db.tables.records.SelfserviceSettingsFlowsRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row13
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SelfserviceSettingsFlows(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SelfserviceSettingsFlowsRecord>?,
    aliased: Table<SelfserviceSettingsFlowsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SelfserviceSettingsFlowsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.selfservice_settings_flows</code>
         */
        val SELFSERVICE_SETTINGS_FLOWS: SelfserviceSettingsFlows = SelfserviceSettingsFlows()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SelfserviceSettingsFlowsRecord> = SelfserviceSettingsFlowsRecord::class.java

    /**
     * The column <code>public.selfservice_settings_flows.id</code>.
     */
    val ID: TableField<SelfserviceSettingsFlowsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.request_url</code>.
     */
    val REQUEST_URL: TableField<SelfserviceSettingsFlowsRecord, String?> = createField(DSL.name("request_url"), SQLDataType.VARCHAR(2048).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.issued_at</code>.
     */
    val ISSUED_AT: TableField<SelfserviceSettingsFlowsRecord, LocalDateTime?> = createField(DSL.name("issued_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.expires_at</code>.
     */
    val EXPIRES_AT: TableField<SelfserviceSettingsFlowsRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.identity_id</code>.
     */
    val IDENTITY_ID: TableField<SelfserviceSettingsFlowsRecord, UUID?> = createField(DSL.name("identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.created_at</code>.
     */
    val CREATED_AT: TableField<SelfserviceSettingsFlowsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.updated_at</code>.
     */
    val UPDATED_AT: TableField<SelfserviceSettingsFlowsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.active_method</code>.
     */
    val ACTIVE_METHOD: TableField<SelfserviceSettingsFlowsRecord, String?> = createField(DSL.name("active_method"), SQLDataType.VARCHAR(32), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.state</code>.
     */
    val STATE: TableField<SelfserviceSettingsFlowsRecord, String?> = createField(DSL.name("state"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field("'show_form'::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.type</code>.
     */
    val TYPE: TableField<SelfserviceSettingsFlowsRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field("'browser'::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.selfservice_settings_flows.ui</code>.
     */
    val UI: TableField<SelfserviceSettingsFlowsRecord, JSONB?> = createField(DSL.name("ui"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.selfservice_settings_flows.nid</code>.
     */
    val NID: TableField<SelfserviceSettingsFlowsRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>public.selfservice_settings_flows.internal_context</code>.
     */
    val INTERNAL_CONTEXT: TableField<SelfserviceSettingsFlowsRecord, JSONB?> = createField(DSL.name("internal_context"), SQLDataType.JSONB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SelfserviceSettingsFlowsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SelfserviceSettingsFlowsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.selfservice_settings_flows</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.selfservice_settings_flows</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.selfservice_settings_flows</code> table reference
     */
    constructor(): this(DSL.name("selfservice_settings_flows"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SelfserviceSettingsFlowsRecord>): this(Internal.createPathAlias(child, key), child, key, SELFSERVICE_SETTINGS_FLOWS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SELFSERVICE_SETTINGS_FLOWS_ID_NID_IDX, SELFSERVICE_SETTINGS_FLOWS_IDENTITY_ID_NID_IDX, SELFSERVICE_SETTINGS_FLOWS_NID_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<SelfserviceSettingsFlowsRecord> = SELFSERVICE_PROFILE_MANAGEMENT_REQUESTS_PKEY
    override fun getReferences(): List<ForeignKey<SelfserviceSettingsFlowsRecord, *>> = listOf(SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_PROFILE_MANAGEMENT_REQUESTS_IDENTITY_ID_FKEY, SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_SETTINGS_FLOWS_NID_FK_IDX)

    private lateinit var _identities: Identities
    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.identities</code> table.
     */
    fun identities(): Identities {
        if (!this::_identities.isInitialized)
            _identities = Identities(this, SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_PROFILE_MANAGEMENT_REQUESTS_IDENTITY_ID_FKEY)

        return _identities;
    }

    val identities: Identities
        get(): Identities = identities()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, SELFSERVICE_SETTINGS_FLOWS__SELFSERVICE_SETTINGS_FLOWS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): SelfserviceSettingsFlows = SelfserviceSettingsFlows(DSL.name(alias), this)
    override fun `as`(alias: Name): SelfserviceSettingsFlows = SelfserviceSettingsFlows(alias, this)
    override fun `as`(alias: Table<*>): SelfserviceSettingsFlows = SelfserviceSettingsFlows(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SelfserviceSettingsFlows = SelfserviceSettingsFlows(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SelfserviceSettingsFlows = SelfserviceSettingsFlows(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SelfserviceSettingsFlows = SelfserviceSettingsFlows(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, String?, String?, JSONB?, UUID?, JSONB?> = super.fieldsRow() as Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, String?, String?, JSONB?, UUID?, JSONB?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, String?, String?, JSONB?, UUID?, JSONB?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, String?, String?, JSONB?, UUID?, JSONB?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
