/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.SELFSERVICE_ERRORS_NID_IDX
import ch.yass.db.keys.SELFSERVICE_ERRORS_PKEY
import ch.yass.db.keys.SELFSERVICE_ERRORS__SELFSERVICE_ERRORS_NID_FK_IDX
import ch.yass.db.tables.records.SelfserviceErrorsRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SelfserviceErrors(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SelfserviceErrorsRecord>?,
    aliased: Table<SelfserviceErrorsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SelfserviceErrorsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.selfservice_errors</code>
         */
        val SELFSERVICE_ERRORS: SelfserviceErrors = SelfserviceErrors()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SelfserviceErrorsRecord> = SelfserviceErrorsRecord::class.java

    /**
     * The column <code>public.selfservice_errors.id</code>.
     */
    val ID: TableField<SelfserviceErrorsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.selfservice_errors.errors</code>.
     */
    val ERRORS: TableField<SelfserviceErrorsRecord, JSONB?> = createField(DSL.name("errors"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.selfservice_errors.seen_at</code>.
     */
    val SEEN_AT: TableField<SelfserviceErrorsRecord, LocalDateTime?> = createField(DSL.name("seen_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.selfservice_errors.was_seen</code>.
     */
    val WAS_SEEN: TableField<SelfserviceErrorsRecord, Boolean?> = createField(DSL.name("was_seen"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.selfservice_errors.created_at</code>.
     */
    val CREATED_AT: TableField<SelfserviceErrorsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_errors.updated_at</code>.
     */
    val UPDATED_AT: TableField<SelfserviceErrorsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_errors.csrf_token</code>.
     */
    val CSRF_TOKEN: TableField<SelfserviceErrorsRecord, String?> = createField(DSL.name("csrf_token"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field("''::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.selfservice_errors.nid</code>.
     */
    val NID: TableField<SelfserviceErrorsRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    private constructor(alias: Name, aliased: Table<SelfserviceErrorsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SelfserviceErrorsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.selfservice_errors</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.selfservice_errors</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.selfservice_errors</code> table reference
     */
    constructor(): this(DSL.name("selfservice_errors"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SelfserviceErrorsRecord>): this(Internal.createPathAlias(child, key), child, key, SELFSERVICE_ERRORS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SELFSERVICE_ERRORS_NID_IDX)
    override fun getPrimaryKey(): UniqueKey<SelfserviceErrorsRecord> = SELFSERVICE_ERRORS_PKEY
    override fun getReferences(): List<ForeignKey<SelfserviceErrorsRecord, *>> = listOf(SELFSERVICE_ERRORS__SELFSERVICE_ERRORS_NID_FK_IDX)

    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, SELFSERVICE_ERRORS__SELFSERVICE_ERRORS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): SelfserviceErrors = SelfserviceErrors(DSL.name(alias), this)
    override fun `as`(alias: Name): SelfserviceErrors = SelfserviceErrors(alias, this)
    override fun `as`(alias: Table<*>): SelfserviceErrors = SelfserviceErrors(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SelfserviceErrors = SelfserviceErrors(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SelfserviceErrors = SelfserviceErrors(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SelfserviceErrors = SelfserviceErrors(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<UUID?, JSONB?, LocalDateTime?, Boolean?, LocalDateTime?, LocalDateTime?, String?, UUID?> = super.fieldsRow() as Row8<UUID?, JSONB?, LocalDateTime?, Boolean?, LocalDateTime?, LocalDateTime?, String?, UUID?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, JSONB?, LocalDateTime?, Boolean?, LocalDateTime?, LocalDateTime?, String?, UUID?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, JSONB?, LocalDateTime?, Boolean?, LocalDateTime?, LocalDateTime?, String?, UUID?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
