/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.SESSIONS_IDENTITY_ID_NID_IDX
import ch.yass.db.indexes.SESSIONS_ID_NID_IDX
import ch.yass.db.indexes.SESSIONS_LOGOUT_TOKEN_UQ_IDX
import ch.yass.db.indexes.SESSIONS_NID_ID_IDENTITY_ID_IDX
import ch.yass.db.indexes.SESSIONS_TOKEN_NID_IDX
import ch.yass.db.indexes.SESSIONS_TOKEN_UQ_IDX
import ch.yass.db.keys.SESSIONS_PKEY
import ch.yass.db.keys.SESSIONS__SESSIONS_IDENTITY_ID_FKEY
import ch.yass.db.keys.SESSIONS__SESSIONS_NID_FK_IDX
import ch.yass.db.tables.records.SessionsRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row13
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Sessions(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SessionsRecord>?,
    aliased: Table<SessionsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SessionsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.sessions</code>
         */
        val SESSIONS: Sessions = Sessions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SessionsRecord> = SessionsRecord::class.java

    /**
     * The column <code>public.sessions.id</code>.
     */
    val ID: TableField<SessionsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.sessions.issued_at</code>.
     */
    val ISSUED_AT: TableField<SessionsRecord, LocalDateTime?> = createField(DSL.name("issued_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.sessions.expires_at</code>.
     */
    val EXPIRES_AT: TableField<SessionsRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.sessions.authenticated_at</code>.
     */
    val AUTHENTICATED_AT: TableField<SessionsRecord, LocalDateTime?> = createField(DSL.name("authenticated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.sessions.identity_id</code>.
     */
    val IDENTITY_ID: TableField<SessionsRecord, UUID?> = createField(DSL.name("identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.sessions.created_at</code>.
     */
    val CREATED_AT: TableField<SessionsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.sessions.updated_at</code>.
     */
    val UPDATED_AT: TableField<SessionsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.sessions.token</code>.
     */
    val TOKEN: TableField<SessionsRecord, String?> = createField(DSL.name("token"), SQLDataType.VARCHAR(39), this, "")

    /**
     * The column <code>public.sessions.active</code>.
     */
    val ACTIVE: TableField<SessionsRecord, Boolean?> = createField(DSL.name("active"), SQLDataType.BOOLEAN.defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.sessions.nid</code>.
     */
    val NID: TableField<SessionsRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.sessions.logout_token</code>.
     */
    val LOGOUT_TOKEN: TableField<SessionsRecord, String?> = createField(DSL.name("logout_token"), SQLDataType.VARCHAR(39), this, "")

    /**
     * The column <code>public.sessions.aal</code>.
     */
    val AAL: TableField<SessionsRecord, String?> = createField(DSL.name("aal"), SQLDataType.VARCHAR(4).nullable(false).defaultValue(DSL.field("'aal1'::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.sessions.authentication_methods</code>.
     */
    val AUTHENTICATION_METHODS: TableField<SessionsRecord, JSONB?> = createField(DSL.name("authentication_methods"), SQLDataType.JSONB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SessionsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SessionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.sessions</code> table reference
     */
    constructor(): this(DSL.name("sessions"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SessionsRecord>): this(Internal.createPathAlias(child, key), child, key, SESSIONS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SESSIONS_ID_NID_IDX, SESSIONS_IDENTITY_ID_NID_IDX, SESSIONS_LOGOUT_TOKEN_UQ_IDX, SESSIONS_NID_ID_IDENTITY_ID_IDX, SESSIONS_TOKEN_NID_IDX, SESSIONS_TOKEN_UQ_IDX)
    override fun getPrimaryKey(): UniqueKey<SessionsRecord> = SESSIONS_PKEY
    override fun getReferences(): List<ForeignKey<SessionsRecord, *>> = listOf(SESSIONS__SESSIONS_IDENTITY_ID_FKEY, SESSIONS__SESSIONS_NID_FK_IDX)

    private lateinit var _identities: Identities
    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.identities</code> table.
     */
    fun identities(): Identities {
        if (!this::_identities.isInitialized)
            _identities = Identities(this, SESSIONS__SESSIONS_IDENTITY_ID_FKEY)

        return _identities;
    }

    val identities: Identities
        get(): Identities = identities()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, SESSIONS__SESSIONS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): Sessions = Sessions(DSL.name(alias), this)
    override fun `as`(alias: Name): Sessions = Sessions(alias, this)
    override fun `as`(alias: Table<*>): Sessions = Sessions(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Sessions = Sessions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Sessions = Sessions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Sessions = Sessions(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?> = super.fieldsRow() as Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
