/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.IDENTITY_VERIFIABLE_ADDRESSES_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_VERIFIABLE_ADDRESSES_NID_IDENTITY_ID_IDX
import ch.yass.db.indexes.IDENTITY_VERIFIABLE_ADDRESSES_NID_ID_IDX
import ch.yass.db.indexes.IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_IDX
import ch.yass.db.indexes.IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_UQ_IDX
import ch.yass.db.keys.IDENTITY_VERIFIABLE_ADDRESSES_PKEY
import ch.yass.db.keys.IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_IDENTITY_ID_FKEY
import ch.yass.db.keys.IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_NID_FK_IDX
import ch.yass.db.tables.records.IdentityVerifiableAddressesRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityVerifiableAddresses(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, IdentityVerifiableAddressesRecord>?,
    aliased: Table<IdentityVerifiableAddressesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<IdentityVerifiableAddressesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.identity_verifiable_addresses</code>
         */
        val IDENTITY_VERIFIABLE_ADDRESSES: IdentityVerifiableAddresses = IdentityVerifiableAddresses()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<IdentityVerifiableAddressesRecord> = IdentityVerifiableAddressesRecord::class.java

    /**
     * The column <code>public.identity_verifiable_addresses.id</code>.
     */
    val ID: TableField<IdentityVerifiableAddressesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.status</code>.
     */
    val STATUS: TableField<IdentityVerifiableAddressesRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.via</code>.
     */
    val VIA: TableField<IdentityVerifiableAddressesRecord, String?> = createField(DSL.name("via"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.verified</code>.
     */
    val VERIFIED: TableField<IdentityVerifiableAddressesRecord, Boolean?> = createField(DSL.name("verified"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.value</code>.
     */
    val VALUE: TableField<IdentityVerifiableAddressesRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(400).nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.verified_at</code>.
     */
    val VERIFIED_AT: TableField<IdentityVerifiableAddressesRecord, LocalDateTime?> = createField(DSL.name("verified_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.identity_id</code>.
     */
    val IDENTITY_ID: TableField<IdentityVerifiableAddressesRecord, UUID?> = createField(DSL.name("identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.created_at</code>.
     */
    val CREATED_AT: TableField<IdentityVerifiableAddressesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.updated_at</code>.
     */
    val UPDATED_AT: TableField<IdentityVerifiableAddressesRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_verifiable_addresses.nid</code>.
     */
    val NID: TableField<IdentityVerifiableAddressesRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    private constructor(alias: Name, aliased: Table<IdentityVerifiableAddressesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<IdentityVerifiableAddressesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.identity_verifiable_addresses</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.identity_verifiable_addresses</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.identity_verifiable_addresses</code> table
     * reference
     */
    constructor(): this(DSL.name("identity_verifiable_addresses"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, IdentityVerifiableAddressesRecord>): this(Internal.createPathAlias(child, key), child, key, IDENTITY_VERIFIABLE_ADDRESSES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDENTITY_VERIFIABLE_ADDRESSES_ID_NID_IDX, IDENTITY_VERIFIABLE_ADDRESSES_NID_ID_IDX, IDENTITY_VERIFIABLE_ADDRESSES_NID_IDENTITY_ID_IDX, IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_IDX, IDENTITY_VERIFIABLE_ADDRESSES_STATUS_VIA_UQ_IDX)
    override fun getPrimaryKey(): UniqueKey<IdentityVerifiableAddressesRecord> = IDENTITY_VERIFIABLE_ADDRESSES_PKEY
    override fun getReferences(): List<ForeignKey<IdentityVerifiableAddressesRecord, *>> = listOf(IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_IDENTITY_ID_FKEY, IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_NID_FK_IDX)

    private lateinit var _identities: Identities
    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.identities</code> table.
     */
    fun identities(): Identities {
        if (!this::_identities.isInitialized)
            _identities = Identities(this, IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_IDENTITY_ID_FKEY)

        return _identities;
    }

    val identities: Identities
        get(): Identities = identities()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, IDENTITY_VERIFIABLE_ADDRESSES__IDENTITY_VERIFIABLE_ADDRESSES_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): IdentityVerifiableAddresses = IdentityVerifiableAddresses(DSL.name(alias), this)
    override fun `as`(alias: Name): IdentityVerifiableAddresses = IdentityVerifiableAddresses(alias, this)
    override fun `as`(alias: Table<*>): IdentityVerifiableAddresses = IdentityVerifiableAddresses(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IdentityVerifiableAddresses = IdentityVerifiableAddresses(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IdentityVerifiableAddresses = IdentityVerifiableAddresses(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IdentityVerifiableAddresses = IdentityVerifiableAddresses(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?> = super.fieldsRow() as Row10<UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, String?, Boolean?, String?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, UUID?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
