/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.IDENTITY_RECOVERY_ADDRESSES_CODE_UQ_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_TOKENS_ID_NID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_TOKENS_NID_ID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_FLOW_ID_IDX
import ch.yass.db.indexes.IDENTITY_RECOVERY_TOKENS_TOKEN_NID_USED_IDX
import ch.yass.db.keys.IDENTITY_RECOVERY_TOKENS_PKEY
import ch.yass.db.keys.IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_ID_FK_IDX
import ch.yass.db.keys.IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_FKEY
import ch.yass.db.keys.IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_NID_FK_IDX
import ch.yass.db.keys.IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_REQUEST_ID_FKEY
import ch.yass.db.tables.records.IdentityRecoveryTokensRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Check
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row13
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityRecoveryTokens(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, IdentityRecoveryTokensRecord>?,
    aliased: Table<IdentityRecoveryTokensRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<IdentityRecoveryTokensRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.identity_recovery_tokens</code>
         */
        val IDENTITY_RECOVERY_TOKENS: IdentityRecoveryTokens = IdentityRecoveryTokens()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<IdentityRecoveryTokensRecord> = IdentityRecoveryTokensRecord::class.java

    /**
     * The column <code>public.identity_recovery_tokens.id</code>.
     */
    val ID: TableField<IdentityRecoveryTokensRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.token</code>.
     */
    val TOKEN: TableField<IdentityRecoveryTokensRecord, String?> = createField(DSL.name("token"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.used</code>.
     */
    val USED: TableField<IdentityRecoveryTokensRecord, Boolean?> = createField(DSL.name("used"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.used_at</code>.
     */
    val USED_AT: TableField<IdentityRecoveryTokensRecord, LocalDateTime?> = createField(DSL.name("used_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column
     * <code>public.identity_recovery_tokens.identity_recovery_address_id</code>.
     */
    val IDENTITY_RECOVERY_ADDRESS_ID: TableField<IdentityRecoveryTokensRecord, UUID?> = createField(DSL.name("identity_recovery_address_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>public.identity_recovery_tokens.selfservice_recovery_flow_id</code>.
     */
    val SELFSERVICE_RECOVERY_FLOW_ID: TableField<IdentityRecoveryTokensRecord, UUID?> = createField(DSL.name("selfservice_recovery_flow_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.identity_recovery_tokens.created_at</code>.
     */
    val CREATED_AT: TableField<IdentityRecoveryTokensRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.updated_at</code>.
     */
    val UPDATED_AT: TableField<IdentityRecoveryTokensRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.expires_at</code>.
     */
    val EXPIRES_AT: TableField<IdentityRecoveryTokensRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2000-01-01 00:00:00'::timestamp without time zone", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.issued_at</code>.
     */
    val ISSUED_AT: TableField<IdentityRecoveryTokensRecord, LocalDateTime?> = createField(DSL.name("issued_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2000-01-01 00:00:00'::timestamp without time zone", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.nid</code>.
     */
    val NID: TableField<IdentityRecoveryTokensRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.identity_recovery_tokens.identity_id</code>.
     */
    val IDENTITY_ID: TableField<IdentityRecoveryTokensRecord, UUID?> = createField(DSL.name("identity_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_recovery_tokens.token_type</code>.
     */
    val TOKEN_TYPE: TableField<IdentityRecoveryTokensRecord, Int?> = createField(DSL.name("token_type"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<IdentityRecoveryTokensRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<IdentityRecoveryTokensRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.identity_recovery_tokens</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.identity_recovery_tokens</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.identity_recovery_tokens</code> table reference
     */
    constructor(): this(DSL.name("identity_recovery_tokens"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, IdentityRecoveryTokensRecord>): this(Internal.createPathAlias(child, key), child, key, IDENTITY_RECOVERY_TOKENS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDENTITY_RECOVERY_ADDRESSES_CODE_UQ_IDX, IDENTITY_RECOVERY_TOKENS_ID_NID_IDX, IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_IDX, IDENTITY_RECOVERY_TOKENS_NID_ID_IDX, IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_FLOW_ID_IDX, IDENTITY_RECOVERY_TOKENS_TOKEN_NID_USED_IDX)
    override fun getPrimaryKey(): UniqueKey<IdentityRecoveryTokensRecord> = IDENTITY_RECOVERY_TOKENS_PKEY
    override fun getReferences(): List<ForeignKey<IdentityRecoveryTokensRecord, *>> = listOf(IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_FKEY, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_REQUEST_ID_FKEY, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_NID_FK_IDX, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_ID_FK_IDX)

    private lateinit var _identityRecoveryAddresses: IdentityRecoveryAddresses
    private lateinit var _selfserviceRecoveryFlows: SelfserviceRecoveryFlows
    private lateinit var _networks: Networks
    private lateinit var _identities: Identities

    /**
     * Get the implicit join path to the
     * <code>public.identity_recovery_addresses</code> table.
     */
    fun identityRecoveryAddresses(): IdentityRecoveryAddresses {
        if (!this::_identityRecoveryAddresses.isInitialized)
            _identityRecoveryAddresses = IdentityRecoveryAddresses(this, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_RECOVERY_ADDRESS_ID_FKEY)

        return _identityRecoveryAddresses;
    }

    val identityRecoveryAddresses: IdentityRecoveryAddresses
        get(): IdentityRecoveryAddresses = identityRecoveryAddresses()

    /**
     * Get the implicit join path to the
     * <code>public.selfservice_recovery_flows</code> table.
     */
    fun selfserviceRecoveryFlows(): SelfserviceRecoveryFlows {
        if (!this::_selfserviceRecoveryFlows.isInitialized)
            _selfserviceRecoveryFlows = SelfserviceRecoveryFlows(this, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_SELFSERVICE_RECOVERY_REQUEST_ID_FKEY)

        return _selfserviceRecoveryFlows;
    }

    val selfserviceRecoveryFlows: SelfserviceRecoveryFlows
        get(): SelfserviceRecoveryFlows = selfserviceRecoveryFlows()

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()

    /**
     * Get the implicit join path to the <code>public.identities</code> table.
     */
    fun identities(): Identities {
        if (!this::_identities.isInitialized)
            _identities = Identities(this, IDENTITY_RECOVERY_TOKENS__IDENTITY_RECOVERY_TOKENS_IDENTITY_ID_FK_IDX)

        return _identities;
    }

    val identities: Identities
        get(): Identities = identities()
    override fun getChecks(): List<Check<IdentityRecoveryTokensRecord>> = listOf(
        Internal.createCheck(this, DSL.name("identity_recovery_tokens_token_type_ck"), "(((token_type = 1) OR (token_type = 2)))", true)
    )
    override fun `as`(alias: String): IdentityRecoveryTokens = IdentityRecoveryTokens(DSL.name(alias), this)
    override fun `as`(alias: Name): IdentityRecoveryTokens = IdentityRecoveryTokens(alias, this)
    override fun `as`(alias: Table<*>): IdentityRecoveryTokens = IdentityRecoveryTokens(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IdentityRecoveryTokens = IdentityRecoveryTokens(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IdentityRecoveryTokens = IdentityRecoveryTokens(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IdentityRecoveryTokens = IdentityRecoveryTokens(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?> = super.fieldsRow() as Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
