/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.IDENTITY_CREDENTIAL_TYPES_NAME_IDX
import ch.yass.db.keys.IDENTITY_CREDENTIAL_TYPES_PKEY
import ch.yass.db.tables.records.IdentityCredentialTypesRecord

import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityCredentialTypes(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, IdentityCredentialTypesRecord>?,
    aliased: Table<IdentityCredentialTypesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<IdentityCredentialTypesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.identity_credential_types</code>
         */
        val IDENTITY_CREDENTIAL_TYPES: IdentityCredentialTypes = IdentityCredentialTypes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<IdentityCredentialTypesRecord> = IdentityCredentialTypesRecord::class.java

    /**
     * The column <code>public.identity_credential_types.id</code>.
     */
    val ID: TableField<IdentityCredentialTypesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.identity_credential_types.name</code>.
     */
    val NAME: TableField<IdentityCredentialTypesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<IdentityCredentialTypesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<IdentityCredentialTypesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.identity_credential_types</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.identity_credential_types</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.identity_credential_types</code> table reference
     */
    constructor(): this(DSL.name("identity_credential_types"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, IdentityCredentialTypesRecord>): this(Internal.createPathAlias(child, key), child, key, IDENTITY_CREDENTIAL_TYPES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDENTITY_CREDENTIAL_TYPES_NAME_IDX)
    override fun getPrimaryKey(): UniqueKey<IdentityCredentialTypesRecord> = IDENTITY_CREDENTIAL_TYPES_PKEY
    override fun `as`(alias: String): IdentityCredentialTypes = IdentityCredentialTypes(DSL.name(alias), this)
    override fun `as`(alias: Name): IdentityCredentialTypes = IdentityCredentialTypes(alias, this)
    override fun `as`(alias: Table<*>): IdentityCredentialTypes = IdentityCredentialTypes(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): IdentityCredentialTypes = IdentityCredentialTypes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): IdentityCredentialTypes = IdentityCredentialTypes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): IdentityCredentialTypes = IdentityCredentialTypes(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<UUID?, String?> = super.fieldsRow() as Row2<UUID?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
