/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.PLAYER_PKEY
import ch.yass.db.tables.records.PlayerRecord

import java.time.LocalDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Player(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlayerRecord>?,
    aliased: Table<PlayerRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlayerRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.player</code>
         */
        val PLAYER: Player = Player()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerRecord> = PlayerRecord::class.java

    /**
     * The column <code>public.player.id</code>.
     */
    val ID: TableField<PlayerRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.player.uuid</code>.
     */
    val UUID: TableField<PlayerRecord, String?> = createField(DSL.name("uuid"), SQLDataType.VARCHAR(37).nullable(false), this, "")

    /**
     * The column <code>public.player.created_at</code>.
     */
    val CREATED_AT: TableField<PlayerRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.player.updated_at</code>.
     */
    val UPDATED_AT: TableField<PlayerRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.player.name</code>.
     */
    val NAME: TableField<PlayerRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.player.bot</code>.
     */
    val BOT: TableField<PlayerRecord, Boolean?> = createField(DSL.name("bot"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<PlayerRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlayerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.player</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.player</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.player</code> table reference
     */
    constructor(): this(DSL.name("player"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlayerRecord>): this(Internal.createPathAlias(child, key), child, key, PLAYER, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PlayerRecord, Int?> = super.getIdentity() as Identity<PlayerRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerRecord> = PLAYER_PKEY
    override fun `as`(alias: String): Player = Player(DSL.name(alias), this)
    override fun `as`(alias: Name): Player = Player(alias, this)
    override fun `as`(alias: Table<*>): Player = Player(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Player = Player(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Player = Player(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Player = Player(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?> = super.fieldsRow() as Row6<Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, LocalDateTime?, LocalDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
