/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.SCHEMA_MIGRATION_VERSION_IDX
import ch.yass.db.indexes.SCHEMA_MIGRATION_VERSION_SELF_IDX
import ch.yass.db.tables.records.SchemaMigrationRecord

import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SchemaMigration(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SchemaMigrationRecord>?,
    aliased: Table<SchemaMigrationRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SchemaMigrationRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.schema_migration</code>
         */
        val SCHEMA_MIGRATION: SchemaMigration = SchemaMigration()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SchemaMigrationRecord> = SchemaMigrationRecord::class.java

    /**
     * The column <code>public.schema_migration.version</code>.
     */
    val VERSION: TableField<SchemaMigrationRecord, String?> = createField(DSL.name("version"), SQLDataType.VARCHAR(48).nullable(false), this, "")

    /**
     * The column <code>public.schema_migration.version_self</code>.
     */
    val VERSION_SELF: TableField<SchemaMigrationRecord, Int?> = createField(DSL.name("version_self"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<SchemaMigrationRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SchemaMigrationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.schema_migration</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.schema_migration</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.schema_migration</code> table reference
     */
    constructor(): this(DSL.name("schema_migration"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SchemaMigrationRecord>): this(Internal.createPathAlias(child, key), child, key, SCHEMA_MIGRATION, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SCHEMA_MIGRATION_VERSION_IDX, SCHEMA_MIGRATION_VERSION_SELF_IDX)
    override fun `as`(alias: String): SchemaMigration = SchemaMigration(DSL.name(alias), this)
    override fun `as`(alias: Name): SchemaMigration = SchemaMigration(alias, this)
    override fun `as`(alias: Table<*>): SchemaMigration = SchemaMigration(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SchemaMigration = SchemaMigration(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SchemaMigration = SchemaMigration(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SchemaMigration = SchemaMigration(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<String?, Int?> = super.fieldsRow() as Row2<String?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
