/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.indexes.SELFSERVICE_REGISTRATION_FLOWS_ID_NID_IDX
import ch.yass.db.indexes.SELFSERVICE_REGISTRATION_FLOWS_NID_ID_IDX
import ch.yass.db.keys.SELFSERVICE_REGISTRATION_FLOWS__SELFSERVICE_REGISTRATION_FLOWS_NID_FK_IDX
import ch.yass.db.keys.SELFSERVICE_REGISTRATION_REQUESTS_PKEY
import ch.yass.db.tables.records.SelfserviceRegistrationFlowsRecord

import java.time.LocalDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row13
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SelfserviceRegistrationFlows(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SelfserviceRegistrationFlowsRecord>?,
    aliased: Table<SelfserviceRegistrationFlowsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SelfserviceRegistrationFlowsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.selfservice_registration_flows</code>
         */
        val SELFSERVICE_REGISTRATION_FLOWS: SelfserviceRegistrationFlows = SelfserviceRegistrationFlows()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SelfserviceRegistrationFlowsRecord> = SelfserviceRegistrationFlowsRecord::class.java

    /**
     * The column <code>public.selfservice_registration_flows.id</code>.
     */
    val ID: TableField<SelfserviceRegistrationFlowsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>public.selfservice_registration_flows.request_url</code>.
     */
    val REQUEST_URL: TableField<SelfserviceRegistrationFlowsRecord, String?> = createField(DSL.name("request_url"), SQLDataType.VARCHAR(2048).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.issued_at</code>.
     */
    val ISSUED_AT: TableField<SelfserviceRegistrationFlowsRecord, LocalDateTime?> = createField(DSL.name("issued_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.expires_at</code>.
     */
    val EXPIRES_AT: TableField<SelfserviceRegistrationFlowsRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column
     * <code>public.selfservice_registration_flows.active_method</code>.
     */
    val ACTIVE_METHOD: TableField<SelfserviceRegistrationFlowsRecord, String?> = createField(DSL.name("active_method"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.csrf_token</code>.
     */
    val CSRF_TOKEN: TableField<SelfserviceRegistrationFlowsRecord, String?> = createField(DSL.name("csrf_token"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.created_at</code>.
     */
    val CREATED_AT: TableField<SelfserviceRegistrationFlowsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.updated_at</code>.
     */
    val UPDATED_AT: TableField<SelfserviceRegistrationFlowsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.type</code>.
     */
    val TYPE: TableField<SelfserviceRegistrationFlowsRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field("'browser'::character varying", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.selfservice_registration_flows.ui</code>.
     */
    val UI: TableField<SelfserviceRegistrationFlowsRecord, JSONB?> = createField(DSL.name("ui"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.selfservice_registration_flows.nid</code>.
     */
    val NID: TableField<SelfserviceRegistrationFlowsRecord, UUID?> = createField(DSL.name("nid"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>public.selfservice_registration_flows.internal_context</code>.
     */
    val INTERNAL_CONTEXT: TableField<SelfserviceRegistrationFlowsRecord, JSONB?> = createField(DSL.name("internal_context"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column
     * <code>public.selfservice_registration_flows.oauth2_login_challenge</code>.
     */
    val OAUTH2_LOGIN_CHALLENGE: TableField<SelfserviceRegistrationFlowsRecord, UUID?> = createField(DSL.name("oauth2_login_challenge"), SQLDataType.UUID, this, "")

    private constructor(alias: Name, aliased: Table<SelfserviceRegistrationFlowsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SelfserviceRegistrationFlowsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.selfservice_registration_flows</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.selfservice_registration_flows</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.selfservice_registration_flows</code> table
     * reference
     */
    constructor(): this(DSL.name("selfservice_registration_flows"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SelfserviceRegistrationFlowsRecord>): this(Internal.createPathAlias(child, key), child, key, SELFSERVICE_REGISTRATION_FLOWS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(SELFSERVICE_REGISTRATION_FLOWS_ID_NID_IDX, SELFSERVICE_REGISTRATION_FLOWS_NID_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<SelfserviceRegistrationFlowsRecord> = SELFSERVICE_REGISTRATION_REQUESTS_PKEY
    override fun getReferences(): List<ForeignKey<SelfserviceRegistrationFlowsRecord, *>> = listOf(SELFSERVICE_REGISTRATION_FLOWS__SELFSERVICE_REGISTRATION_FLOWS_NID_FK_IDX)

    private lateinit var _networks: Networks

    /**
     * Get the implicit join path to the <code>public.networks</code> table.
     */
    fun networks(): Networks {
        if (!this::_networks.isInitialized)
            _networks = Networks(this, SELFSERVICE_REGISTRATION_FLOWS__SELFSERVICE_REGISTRATION_FLOWS_NID_FK_IDX)

        return _networks;
    }

    val networks: Networks
        get(): Networks = networks()
    override fun `as`(alias: String): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(DSL.name(alias), this)
    override fun `as`(alias: Name): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(alias, this)
    override fun `as`(alias: Table<*>): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SelfserviceRegistrationFlows = SelfserviceRegistrationFlows(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?> = super.fieldsRow() as Row13<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, String?, JSONB?, UUID?, JSONB?, UUID?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
