/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables


import ch.yass.db.Public
import ch.yass.db.keys.TRICK_PKEY
import ch.yass.db.keys.TRICK__FK_TRICK_ON_HAND
import ch.yass.db.keys.TRICK__FK_TRICK_ON_WINNER
import ch.yass.db.tables.records.TrickRecord

import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Trick(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TrickRecord>?,
    aliased: Table<TrickRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TrickRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.trick</code>
         */
        val TRICK: Trick = Trick()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TrickRecord> = TrickRecord::class.java

    /**
     * The column <code>public.trick.id</code>.
     */
    val ID: TableField<TrickRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.trick.uuid</code>.
     */
    val UUID: TableField<TrickRecord, String?> = createField(DSL.name("uuid"), SQLDataType.VARCHAR(37), this, "")

    /**
     * The column <code>public.trick.created_at</code>.
     */
    val CREATED_AT: TableField<TrickRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.trick.updated_at</code>.
     */
    val UPDATED_AT: TableField<TrickRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.trick.hand_id</code>.
     */
    val HAND_ID: TableField<TrickRecord, Int?> = createField(DSL.name("hand_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.trick.winner_id</code>.
     */
    val WINNER_ID: TableField<TrickRecord, Int?> = createField(DSL.name("winner_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.trick.points</code>.
     */
    val POINTS: TableField<TrickRecord, Int?> = createField(DSL.name("points"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TrickRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TrickRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.trick</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.trick</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.trick</code> table reference
     */
    constructor(): this(DSL.name("trick"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TrickRecord>): this(Internal.createPathAlias(child, key), child, key, TRICK, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<TrickRecord, Int?> = super.getIdentity() as Identity<TrickRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TrickRecord> = TRICK_PKEY
    override fun getReferences(): List<ForeignKey<TrickRecord, *>> = listOf(TRICK__FK_TRICK_ON_HAND, TRICK__FK_TRICK_ON_WINNER)

    private lateinit var _hand: Hand
    private lateinit var _player: Player

    /**
     * Get the implicit join path to the <code>public.hand</code> table.
     */
    fun hand(): Hand {
        if (!this::_hand.isInitialized)
            _hand = Hand(this, TRICK__FK_TRICK_ON_HAND)

        return _hand;
    }

    val hand: Hand
        get(): Hand = hand()

    /**
     * Get the implicit join path to the <code>public.player</code> table.
     */
    fun player(): Player {
        if (!this::_player.isInitialized)
            _player = Player(this, TRICK__FK_TRICK_ON_WINNER)

        return _player;
    }

    val player: Player
        get(): Player = player()
    override fun `as`(alias: String): Trick = Trick(DSL.name(alias), this)
    override fun `as`(alias: Name): Trick = Trick(alias, this)
    override fun `as`(alias: Table<*>): Trick = Trick(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Trick = Trick(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Trick = Trick(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Trick = Trick(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?> = super.fieldsRow() as Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
