/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.ContinuityContainers

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ContinuityContainersRecord() : UpdatableRecordImpl<ContinuityContainersRecord>(ContinuityContainers.CONTINUITY_CONTAINERS), Record8<UUID?, UUID?, String?, JSONB?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var identityId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var payload: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(7, value)
        get(): UUID? = get(7) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<UUID?, UUID?, String?, JSONB?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?> = super.fieldsRow() as Row8<UUID?, UUID?, String?, JSONB?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun valuesRow(): Row8<UUID?, UUID?, String?, JSONB?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?> = super.valuesRow() as Row8<UUID?, UUID?, String?, JSONB?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?>
    override fun field1(): Field<UUID?> = ContinuityContainers.CONTINUITY_CONTAINERS.ID
    override fun field2(): Field<UUID?> = ContinuityContainers.CONTINUITY_CONTAINERS.IDENTITY_ID
    override fun field3(): Field<String?> = ContinuityContainers.CONTINUITY_CONTAINERS.NAME
    override fun field4(): Field<JSONB?> = ContinuityContainers.CONTINUITY_CONTAINERS.PAYLOAD
    override fun field5(): Field<LocalDateTime?> = ContinuityContainers.CONTINUITY_CONTAINERS.EXPIRES_AT
    override fun field6(): Field<LocalDateTime?> = ContinuityContainers.CONTINUITY_CONTAINERS.CREATED_AT
    override fun field7(): Field<LocalDateTime?> = ContinuityContainers.CONTINUITY_CONTAINERS.UPDATED_AT
    override fun field8(): Field<UUID?> = ContinuityContainers.CONTINUITY_CONTAINERS.NID
    override fun component1(): UUID? = id
    override fun component2(): UUID? = identityId
    override fun component3(): String? = name
    override fun component4(): JSONB? = payload
    override fun component5(): LocalDateTime? = expiresAt
    override fun component6(): LocalDateTime? = createdAt
    override fun component7(): LocalDateTime? = updatedAt
    override fun component8(): UUID? = nid
    override fun value1(): UUID? = id
    override fun value2(): UUID? = identityId
    override fun value3(): String? = name
    override fun value4(): JSONB? = payload
    override fun value5(): LocalDateTime? = expiresAt
    override fun value6(): LocalDateTime? = createdAt
    override fun value7(): LocalDateTime? = updatedAt
    override fun value8(): UUID? = nid

    override fun value1(value: UUID?): ContinuityContainersRecord {
        this.id = value
        return this
    }

    override fun value2(value: UUID?): ContinuityContainersRecord {
        this.identityId = value
        return this
    }

    override fun value3(value: String?): ContinuityContainersRecord {
        this.name = value
        return this
    }

    override fun value4(value: JSONB?): ContinuityContainersRecord {
        this.payload = value
        return this
    }

    override fun value5(value: LocalDateTime?): ContinuityContainersRecord {
        this.expiresAt = value
        return this
    }

    override fun value6(value: LocalDateTime?): ContinuityContainersRecord {
        this.createdAt = value
        return this
    }

    override fun value7(value: LocalDateTime?): ContinuityContainersRecord {
        this.updatedAt = value
        return this
    }

    override fun value8(value: UUID?): ContinuityContainersRecord {
        this.nid = value
        return this
    }

    override fun values(value1: UUID?, value2: UUID?, value3: String?, value4: JSONB?, value5: LocalDateTime?, value6: LocalDateTime?, value7: LocalDateTime?, value8: UUID?): ContinuityContainersRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised ContinuityContainersRecord
     */
    constructor(id: UUID? = null, identityId: UUID? = null, name: String? = null, payload: JSONB? = null, expiresAt: LocalDateTime? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, nid: UUID? = null): this() {
        this.id = id
        this.identityId = identityId
        this.name = name
        this.payload = payload
        this.expiresAt = expiresAt
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.nid = nid
    }

    /**
     * Create a detached, initialised ContinuityContainersRecord
     */
    constructor(value: ch.yass.db.tables.pojos.ContinuityContainers?): this() {
        if (value != null) {
            this.id = value.id
            this.identityId = value.identityId
            this.name = value.name
            this.payload = value.payload
            this.expiresAt = value.expiresAt
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.nid = value.nid
        }
    }
}
