/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Hand

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.JSON
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class HandRecord() : UpdatableRecordImpl<HandRecord>(Hand.HAND), Record13<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Boolean?, Int?, JSON?, JSON?, JSON?, JSON?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var gameId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var startingPlayerId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var trump: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var gschobe: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var points: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var north: JSON?
        set(value): Unit = set(9, value)
        get(): JSON? = get(9) as JSON?

    open var east: JSON?
        set(value): Unit = set(10, value)
        get(): JSON? = get(10) as JSON?

    open var south: JSON?
        set(value): Unit = set(11, value)
        get(): JSON? = get(11) as JSON?

    open var west: JSON?
        set(value): Unit = set(12, value)
        get(): JSON? = get(12) as JSON?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Boolean?, Int?, JSON?, JSON?, JSON?, JSON?> = super.fieldsRow() as Row13<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Boolean?, Int?, JSON?, JSON?, JSON?, JSON?>
    override fun valuesRow(): Row13<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Boolean?, Int?, JSON?, JSON?, JSON?, JSON?> = super.valuesRow() as Row13<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Boolean?, Int?, JSON?, JSON?, JSON?, JSON?>
    override fun field1(): Field<Int?> = Hand.HAND.ID
    override fun field2(): Field<String?> = Hand.HAND.UUID
    override fun field3(): Field<LocalDateTime?> = Hand.HAND.CREATED_AT
    override fun field4(): Field<LocalDateTime?> = Hand.HAND.UPDATED_AT
    override fun field5(): Field<Int?> = Hand.HAND.GAME_ID
    override fun field6(): Field<Int?> = Hand.HAND.STARTING_PLAYER_ID
    override fun field7(): Field<Int?> = Hand.HAND.TRUMP
    override fun field8(): Field<Boolean?> = Hand.HAND.GSCHOBE
    override fun field9(): Field<Int?> = Hand.HAND.POINTS
    override fun field10(): Field<JSON?> = Hand.HAND.NORTH
    override fun field11(): Field<JSON?> = Hand.HAND.EAST
    override fun field12(): Field<JSON?> = Hand.HAND.SOUTH
    override fun field13(): Field<JSON?> = Hand.HAND.WEST
    override fun component1(): Int? = id
    override fun component2(): String? = uuid
    override fun component3(): LocalDateTime? = createdAt
    override fun component4(): LocalDateTime? = updatedAt
    override fun component5(): Int? = gameId
    override fun component6(): Int? = startingPlayerId
    override fun component7(): Int? = trump
    override fun component8(): Boolean? = gschobe
    override fun component9(): Int? = points
    override fun component10(): JSON? = north
    override fun component11(): JSON? = east
    override fun component12(): JSON? = south
    override fun component13(): JSON? = west
    override fun value1(): Int? = id
    override fun value2(): String? = uuid
    override fun value3(): LocalDateTime? = createdAt
    override fun value4(): LocalDateTime? = updatedAt
    override fun value5(): Int? = gameId
    override fun value6(): Int? = startingPlayerId
    override fun value7(): Int? = trump
    override fun value8(): Boolean? = gschobe
    override fun value9(): Int? = points
    override fun value10(): JSON? = north
    override fun value11(): JSON? = east
    override fun value12(): JSON? = south
    override fun value13(): JSON? = west

    override fun value1(value: Int?): HandRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): HandRecord {
        this.uuid = value
        return this
    }

    override fun value3(value: LocalDateTime?): HandRecord {
        this.createdAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): HandRecord {
        this.updatedAt = value
        return this
    }

    override fun value5(value: Int?): HandRecord {
        this.gameId = value
        return this
    }

    override fun value6(value: Int?): HandRecord {
        this.startingPlayerId = value
        return this
    }

    override fun value7(value: Int?): HandRecord {
        this.trump = value
        return this
    }

    override fun value8(value: Boolean?): HandRecord {
        this.gschobe = value
        return this
    }

    override fun value9(value: Int?): HandRecord {
        this.points = value
        return this
    }

    override fun value10(value: JSON?): HandRecord {
        this.north = value
        return this
    }

    override fun value11(value: JSON?): HandRecord {
        this.east = value
        return this
    }

    override fun value12(value: JSON?): HandRecord {
        this.south = value
        return this
    }

    override fun value13(value: JSON?): HandRecord {
        this.west = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: Int?, value6: Int?, value7: Int?, value8: Boolean?, value9: Int?, value10: JSON?, value11: JSON?, value12: JSON?, value13: JSON?): HandRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised HandRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, gameId: Int? = null, startingPlayerId: Int? = null, trump: Int? = null, gschobe: Boolean? = null, points: Int? = null, north: JSON? = null, east: JSON? = null, south: JSON? = null, west: JSON? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.gameId = gameId
        this.startingPlayerId = startingPlayerId
        this.trump = trump
        this.gschobe = gschobe
        this.points = points
        this.north = north
        this.east = east
        this.south = south
        this.west = west
    }

    /**
     * Create a detached, initialised HandRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Hand?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.gameId = value.gameId
            this.startingPlayerId = value.startingPlayerId
            this.trump = value.trump
            this.gschobe = value.gschobe
            this.points = value.points
            this.north = value.north
            this.east = value.east
            this.south = value.south
            this.west = value.west
        }
    }
}
