/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityRecoveryTokens

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityRecoveryTokensRecord() : UpdatableRecordImpl<IdentityRecoveryTokensRecord>(IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS), Record13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var token: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var used: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open var usedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var identityRecoveryAddressId: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var selfserviceRecoveryFlowId: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(10, value)
        get(): UUID? = get(10) as UUID?

    open var identityId: UUID?
        set(value): Unit = set(11, value)
        get(): UUID? = get(11) as UUID?

    open var tokenType: Int?
        set(value): Unit = set(12, value)
        get(): Int? = get(12) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?> = super.fieldsRow() as Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?>
    override fun valuesRow(): Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?> = super.valuesRow() as Row13<UUID?, String?, Boolean?, LocalDateTime?, UUID?, UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, UUID?, Int?>
    override fun field1(): Field<UUID?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.ID
    override fun field2(): Field<String?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.TOKEN
    override fun field3(): Field<Boolean?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.USED
    override fun field4(): Field<LocalDateTime?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.USED_AT
    override fun field5(): Field<UUID?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.IDENTITY_RECOVERY_ADDRESS_ID
    override fun field6(): Field<UUID?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.SELFSERVICE_RECOVERY_FLOW_ID
    override fun field7(): Field<LocalDateTime?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.CREATED_AT
    override fun field8(): Field<LocalDateTime?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.UPDATED_AT
    override fun field9(): Field<LocalDateTime?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.EXPIRES_AT
    override fun field10(): Field<LocalDateTime?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.ISSUED_AT
    override fun field11(): Field<UUID?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.NID
    override fun field12(): Field<UUID?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.IDENTITY_ID
    override fun field13(): Field<Int?> = IdentityRecoveryTokens.IDENTITY_RECOVERY_TOKENS.TOKEN_TYPE
    override fun component1(): UUID? = id
    override fun component2(): String? = token
    override fun component3(): Boolean? = used
    override fun component4(): LocalDateTime? = usedAt
    override fun component5(): UUID? = identityRecoveryAddressId
    override fun component6(): UUID? = selfserviceRecoveryFlowId
    override fun component7(): LocalDateTime? = createdAt
    override fun component8(): LocalDateTime? = updatedAt
    override fun component9(): LocalDateTime? = expiresAt
    override fun component10(): LocalDateTime? = issuedAt
    override fun component11(): UUID? = nid
    override fun component12(): UUID? = identityId
    override fun component13(): Int? = tokenType
    override fun value1(): UUID? = id
    override fun value2(): String? = token
    override fun value3(): Boolean? = used
    override fun value4(): LocalDateTime? = usedAt
    override fun value5(): UUID? = identityRecoveryAddressId
    override fun value6(): UUID? = selfserviceRecoveryFlowId
    override fun value7(): LocalDateTime? = createdAt
    override fun value8(): LocalDateTime? = updatedAt
    override fun value9(): LocalDateTime? = expiresAt
    override fun value10(): LocalDateTime? = issuedAt
    override fun value11(): UUID? = nid
    override fun value12(): UUID? = identityId
    override fun value13(): Int? = tokenType

    override fun value1(value: UUID?): IdentityRecoveryTokensRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityRecoveryTokensRecord {
        this.token = value
        return this
    }

    override fun value3(value: Boolean?): IdentityRecoveryTokensRecord {
        this.used = value
        return this
    }

    override fun value4(value: LocalDateTime?): IdentityRecoveryTokensRecord {
        this.usedAt = value
        return this
    }

    override fun value5(value: UUID?): IdentityRecoveryTokensRecord {
        this.identityRecoveryAddressId = value
        return this
    }

    override fun value6(value: UUID?): IdentityRecoveryTokensRecord {
        this.selfserviceRecoveryFlowId = value
        return this
    }

    override fun value7(value: LocalDateTime?): IdentityRecoveryTokensRecord {
        this.createdAt = value
        return this
    }

    override fun value8(value: LocalDateTime?): IdentityRecoveryTokensRecord {
        this.updatedAt = value
        return this
    }

    override fun value9(value: LocalDateTime?): IdentityRecoveryTokensRecord {
        this.expiresAt = value
        return this
    }

    override fun value10(value: LocalDateTime?): IdentityRecoveryTokensRecord {
        this.issuedAt = value
        return this
    }

    override fun value11(value: UUID?): IdentityRecoveryTokensRecord {
        this.nid = value
        return this
    }

    override fun value12(value: UUID?): IdentityRecoveryTokensRecord {
        this.identityId = value
        return this
    }

    override fun value13(value: Int?): IdentityRecoveryTokensRecord {
        this.tokenType = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: Boolean?, value4: LocalDateTime?, value5: UUID?, value6: UUID?, value7: LocalDateTime?, value8: LocalDateTime?, value9: LocalDateTime?, value10: LocalDateTime?, value11: UUID?, value12: UUID?, value13: Int?): IdentityRecoveryTokensRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised IdentityRecoveryTokensRecord
     */
    constructor(id: UUID? = null, token: String? = null, used: Boolean? = null, usedAt: LocalDateTime? = null, identityRecoveryAddressId: UUID? = null, selfserviceRecoveryFlowId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, expiresAt: LocalDateTime? = null, issuedAt: LocalDateTime? = null, nid: UUID? = null, identityId: UUID? = null, tokenType: Int? = null): this() {
        this.id = id
        this.token = token
        this.used = used
        this.usedAt = usedAt
        this.identityRecoveryAddressId = identityRecoveryAddressId
        this.selfserviceRecoveryFlowId = selfserviceRecoveryFlowId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.expiresAt = expiresAt
        this.issuedAt = issuedAt
        this.nid = nid
        this.identityId = identityId
        this.tokenType = tokenType
    }

    /**
     * Create a detached, initialised IdentityRecoveryTokensRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityRecoveryTokens?): this() {
        if (value != null) {
            this.id = value.id
            this.token = value.token
            this.used = value.used
            this.usedAt = value.usedAt
            this.identityRecoveryAddressId = value.identityRecoveryAddressId
            this.selfserviceRecoveryFlowId = value.selfserviceRecoveryFlowId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.expiresAt = value.expiresAt
            this.issuedAt = value.issuedAt
            this.nid = value.nid
            this.identityId = value.identityId
            this.tokenType = value.tokenType
        }
    }
}
