/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityCredentialIdentifiers

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityCredentialIdentifiersRecord() : UpdatableRecordImpl<IdentityCredentialIdentifiersRecord>(IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS), Record7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var identifier: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var identityCredentialId: UUID?
        set(value): Unit = set(2, value)
        get(): UUID? = get(2) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var nid: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var identityCredentialTypeId: UUID?
        set(value): Unit = set(6, value)
        get(): UUID? = get(6) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?> = super.fieldsRow() as Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?>
    override fun valuesRow(): Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?> = super.valuesRow() as Row7<UUID?, String?, UUID?, LocalDateTime?, LocalDateTime?, UUID?, UUID?>
    override fun field1(): Field<UUID?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.ID
    override fun field2(): Field<String?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTIFIER
    override fun field3(): Field<UUID?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTITY_CREDENTIAL_ID
    override fun field4(): Field<LocalDateTime?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.CREATED_AT
    override fun field5(): Field<LocalDateTime?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.UPDATED_AT
    override fun field6(): Field<UUID?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.NID
    override fun field7(): Field<UUID?> = IdentityCredentialIdentifiers.IDENTITY_CREDENTIAL_IDENTIFIERS.IDENTITY_CREDENTIAL_TYPE_ID
    override fun component1(): UUID? = id
    override fun component2(): String? = identifier
    override fun component3(): UUID? = identityCredentialId
    override fun component4(): LocalDateTime? = createdAt
    override fun component5(): LocalDateTime? = updatedAt
    override fun component6(): UUID? = nid
    override fun component7(): UUID? = identityCredentialTypeId
    override fun value1(): UUID? = id
    override fun value2(): String? = identifier
    override fun value3(): UUID? = identityCredentialId
    override fun value4(): LocalDateTime? = createdAt
    override fun value5(): LocalDateTime? = updatedAt
    override fun value6(): UUID? = nid
    override fun value7(): UUID? = identityCredentialTypeId

    override fun value1(value: UUID?): IdentityCredentialIdentifiersRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityCredentialIdentifiersRecord {
        this.identifier = value
        return this
    }

    override fun value3(value: UUID?): IdentityCredentialIdentifiersRecord {
        this.identityCredentialId = value
        return this
    }

    override fun value4(value: LocalDateTime?): IdentityCredentialIdentifiersRecord {
        this.createdAt = value
        return this
    }

    override fun value5(value: LocalDateTime?): IdentityCredentialIdentifiersRecord {
        this.updatedAt = value
        return this
    }

    override fun value6(value: UUID?): IdentityCredentialIdentifiersRecord {
        this.nid = value
        return this
    }

    override fun value7(value: UUID?): IdentityCredentialIdentifiersRecord {
        this.identityCredentialTypeId = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: UUID?, value4: LocalDateTime?, value5: LocalDateTime?, value6: UUID?, value7: UUID?): IdentityCredentialIdentifiersRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised IdentityCredentialIdentifiersRecord
     */
    constructor(id: UUID? = null, identifier: String? = null, identityCredentialId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, nid: UUID? = null, identityCredentialTypeId: UUID? = null): this() {
        this.id = id
        this.identifier = identifier
        this.identityCredentialId = identityCredentialId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.nid = nid
        this.identityCredentialTypeId = identityCredentialTypeId
    }

    /**
     * Create a detached, initialised IdentityCredentialIdentifiersRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityCredentialIdentifiers?): this() {
        if (value != null) {
            this.id = value.id
            this.identifier = value.identifier
            this.identityCredentialId = value.identityCredentialId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.nid = value.nid
            this.identityCredentialTypeId = value.identityCredentialTypeId
        }
    }
}
