/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.IdentityCredentialTypes

import java.util.UUID

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class IdentityCredentialTypesRecord() : UpdatableRecordImpl<IdentityCredentialTypesRecord>(IdentityCredentialTypes.IDENTITY_CREDENTIAL_TYPES), Record2<UUID?, String?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<UUID?, String?> = super.fieldsRow() as Row2<UUID?, String?>
    override fun valuesRow(): Row2<UUID?, String?> = super.valuesRow() as Row2<UUID?, String?>
    override fun field1(): Field<UUID?> = IdentityCredentialTypes.IDENTITY_CREDENTIAL_TYPES.ID
    override fun field2(): Field<String?> = IdentityCredentialTypes.IDENTITY_CREDENTIAL_TYPES.NAME
    override fun component1(): UUID? = id
    override fun component2(): String? = name
    override fun value1(): UUID? = id
    override fun value2(): String? = name

    override fun value1(value: UUID?): IdentityCredentialTypesRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): IdentityCredentialTypesRecord {
        this.name = value
        return this
    }

    override fun values(value1: UUID?, value2: String?): IdentityCredentialTypesRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised IdentityCredentialTypesRecord
     */
    constructor(id: UUID? = null, name: String? = null): this() {
        this.id = id
        this.name = name
    }

    /**
     * Create a detached, initialised IdentityCredentialTypesRecord
     */
    constructor(value: ch.yass.db.tables.pojos.IdentityCredentialTypes?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
        }
    }
}
