/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.SelfserviceLoginFlows

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record15
import org.jooq.Row15
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SelfserviceLoginFlowsRecord() : UpdatableRecordImpl<SelfserviceLoginFlowsRecord>(SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS), Record15<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, Boolean?, String?, JSONB?, UUID?, String?, JSONB?, UUID?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var requestUrl: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var activeMethod: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var csrfToken: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var forced: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    open var type: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var ui: JSONB?
        set(value): Unit = set(10, value)
        get(): JSONB? = get(10) as JSONB?

    open var nid: UUID?
        set(value): Unit = set(11, value)
        get(): UUID? = get(11) as UUID?

    open var requestedAal: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var internalContext: JSONB?
        set(value): Unit = set(13, value)
        get(): JSONB? = get(13) as JSONB?

    open var oauth2LoginChallenge: UUID?
        set(value): Unit = set(14, value)
        get(): UUID? = get(14) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row15<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, Boolean?, String?, JSONB?, UUID?, String?, JSONB?, UUID?> = super.fieldsRow() as Row15<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, Boolean?, String?, JSONB?, UUID?, String?, JSONB?, UUID?>
    override fun valuesRow(): Row15<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, Boolean?, String?, JSONB?, UUID?, String?, JSONB?, UUID?> = super.valuesRow() as Row15<UUID?, String?, LocalDateTime?, LocalDateTime?, String?, String?, LocalDateTime?, LocalDateTime?, Boolean?, String?, JSONB?, UUID?, String?, JSONB?, UUID?>
    override fun field1(): Field<UUID?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.ID
    override fun field2(): Field<String?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.REQUEST_URL
    override fun field3(): Field<LocalDateTime?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.ISSUED_AT
    override fun field4(): Field<LocalDateTime?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.EXPIRES_AT
    override fun field5(): Field<String?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.ACTIVE_METHOD
    override fun field6(): Field<String?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.CSRF_TOKEN
    override fun field7(): Field<LocalDateTime?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.CREATED_AT
    override fun field8(): Field<LocalDateTime?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.UPDATED_AT
    override fun field9(): Field<Boolean?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.FORCED
    override fun field10(): Field<String?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.TYPE
    override fun field11(): Field<JSONB?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.UI
    override fun field12(): Field<UUID?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.NID
    override fun field13(): Field<String?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.REQUESTED_AAL
    override fun field14(): Field<JSONB?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.INTERNAL_CONTEXT
    override fun field15(): Field<UUID?> = SelfserviceLoginFlows.SELFSERVICE_LOGIN_FLOWS.OAUTH2_LOGIN_CHALLENGE
    override fun component1(): UUID? = id
    override fun component2(): String? = requestUrl
    override fun component3(): LocalDateTime? = issuedAt
    override fun component4(): LocalDateTime? = expiresAt
    override fun component5(): String? = activeMethod
    override fun component6(): String? = csrfToken
    override fun component7(): LocalDateTime? = createdAt
    override fun component8(): LocalDateTime? = updatedAt
    override fun component9(): Boolean? = forced
    override fun component10(): String? = type
    override fun component11(): JSONB? = ui
    override fun component12(): UUID? = nid
    override fun component13(): String? = requestedAal
    override fun component14(): JSONB? = internalContext
    override fun component15(): UUID? = oauth2LoginChallenge
    override fun value1(): UUID? = id
    override fun value2(): String? = requestUrl
    override fun value3(): LocalDateTime? = issuedAt
    override fun value4(): LocalDateTime? = expiresAt
    override fun value5(): String? = activeMethod
    override fun value6(): String? = csrfToken
    override fun value7(): LocalDateTime? = createdAt
    override fun value8(): LocalDateTime? = updatedAt
    override fun value9(): Boolean? = forced
    override fun value10(): String? = type
    override fun value11(): JSONB? = ui
    override fun value12(): UUID? = nid
    override fun value13(): String? = requestedAal
    override fun value14(): JSONB? = internalContext
    override fun value15(): UUID? = oauth2LoginChallenge

    override fun value1(value: UUID?): SelfserviceLoginFlowsRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SelfserviceLoginFlowsRecord {
        this.requestUrl = value
        return this
    }

    override fun value3(value: LocalDateTime?): SelfserviceLoginFlowsRecord {
        this.issuedAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): SelfserviceLoginFlowsRecord {
        this.expiresAt = value
        return this
    }

    override fun value5(value: String?): SelfserviceLoginFlowsRecord {
        this.activeMethod = value
        return this
    }

    override fun value6(value: String?): SelfserviceLoginFlowsRecord {
        this.csrfToken = value
        return this
    }

    override fun value7(value: LocalDateTime?): SelfserviceLoginFlowsRecord {
        this.createdAt = value
        return this
    }

    override fun value8(value: LocalDateTime?): SelfserviceLoginFlowsRecord {
        this.updatedAt = value
        return this
    }

    override fun value9(value: Boolean?): SelfserviceLoginFlowsRecord {
        this.forced = value
        return this
    }

    override fun value10(value: String?): SelfserviceLoginFlowsRecord {
        this.type = value
        return this
    }

    override fun value11(value: JSONB?): SelfserviceLoginFlowsRecord {
        this.ui = value
        return this
    }

    override fun value12(value: UUID?): SelfserviceLoginFlowsRecord {
        this.nid = value
        return this
    }

    override fun value13(value: String?): SelfserviceLoginFlowsRecord {
        this.requestedAal = value
        return this
    }

    override fun value14(value: JSONB?): SelfserviceLoginFlowsRecord {
        this.internalContext = value
        return this
    }

    override fun value15(value: UUID?): SelfserviceLoginFlowsRecord {
        this.oauth2LoginChallenge = value
        return this
    }

    override fun values(value1: UUID?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: String?, value6: String?, value7: LocalDateTime?, value8: LocalDateTime?, value9: Boolean?, value10: String?, value11: JSONB?, value12: UUID?, value13: String?, value14: JSONB?, value15: UUID?): SelfserviceLoginFlowsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        return this
    }

    /**
     * Create a detached, initialised SelfserviceLoginFlowsRecord
     */
    constructor(id: UUID? = null, requestUrl: String? = null, issuedAt: LocalDateTime? = null, expiresAt: LocalDateTime? = null, activeMethod: String? = null, csrfToken: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, forced: Boolean? = null, type: String? = null, ui: JSONB? = null, nid: UUID? = null, requestedAal: String? = null, internalContext: JSONB? = null, oauth2LoginChallenge: UUID? = null): this() {
        this.id = id
        this.requestUrl = requestUrl
        this.issuedAt = issuedAt
        this.expiresAt = expiresAt
        this.activeMethod = activeMethod
        this.csrfToken = csrfToken
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.forced = forced
        this.type = type
        this.ui = ui
        this.nid = nid
        this.requestedAal = requestedAal
        this.internalContext = internalContext
        this.oauth2LoginChallenge = oauth2LoginChallenge
    }

    /**
     * Create a detached, initialised SelfserviceLoginFlowsRecord
     */
    constructor(value: ch.yass.db.tables.pojos.SelfserviceLoginFlows?): this() {
        if (value != null) {
            this.id = value.id
            this.requestUrl = value.requestUrl
            this.issuedAt = value.issuedAt
            this.expiresAt = value.expiresAt
            this.activeMethod = value.activeMethod
            this.csrfToken = value.csrfToken
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.forced = value.forced
            this.type = value.type
            this.ui = value.ui
            this.nid = value.nid
            this.requestedAal = value.requestedAal
            this.internalContext = value.internalContext
            this.oauth2LoginChallenge = value.oauth2LoginChallenge
        }
    }
}
