/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Sessions

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Field
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SessionsRecord() : UpdatableRecordImpl<SessionsRecord>(Sessions.SESSIONS), Record13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?> {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var issuedAt: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var expiresAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var authenticatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var identityId: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var token: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var active: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    open var nid: UUID?
        set(value): Unit = set(9, value)
        get(): UUID? = get(9) as UUID?

    open var logoutToken: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var aal: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var authenticationMethods: JSONB?
        set(value): Unit = set(12, value)
        get(): JSONB? = get(12) as JSONB?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?> = super.fieldsRow() as Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?>
    override fun valuesRow(): Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?> = super.valuesRow() as Row13<UUID?, LocalDateTime?, LocalDateTime?, LocalDateTime?, UUID?, LocalDateTime?, LocalDateTime?, String?, Boolean?, UUID?, String?, String?, JSONB?>
    override fun field1(): Field<UUID?> = Sessions.SESSIONS.ID
    override fun field2(): Field<LocalDateTime?> = Sessions.SESSIONS.ISSUED_AT
    override fun field3(): Field<LocalDateTime?> = Sessions.SESSIONS.EXPIRES_AT
    override fun field4(): Field<LocalDateTime?> = Sessions.SESSIONS.AUTHENTICATED_AT
    override fun field5(): Field<UUID?> = Sessions.SESSIONS.IDENTITY_ID
    override fun field6(): Field<LocalDateTime?> = Sessions.SESSIONS.CREATED_AT
    override fun field7(): Field<LocalDateTime?> = Sessions.SESSIONS.UPDATED_AT
    override fun field8(): Field<String?> = Sessions.SESSIONS.TOKEN
    override fun field9(): Field<Boolean?> = Sessions.SESSIONS.ACTIVE
    override fun field10(): Field<UUID?> = Sessions.SESSIONS.NID
    override fun field11(): Field<String?> = Sessions.SESSIONS.LOGOUT_TOKEN
    override fun field12(): Field<String?> = Sessions.SESSIONS.AAL
    override fun field13(): Field<JSONB?> = Sessions.SESSIONS.AUTHENTICATION_METHODS
    override fun component1(): UUID? = id
    override fun component2(): LocalDateTime? = issuedAt
    override fun component3(): LocalDateTime? = expiresAt
    override fun component4(): LocalDateTime? = authenticatedAt
    override fun component5(): UUID? = identityId
    override fun component6(): LocalDateTime? = createdAt
    override fun component7(): LocalDateTime? = updatedAt
    override fun component8(): String? = token
    override fun component9(): Boolean? = active
    override fun component10(): UUID? = nid
    override fun component11(): String? = logoutToken
    override fun component12(): String? = aal
    override fun component13(): JSONB? = authenticationMethods
    override fun value1(): UUID? = id
    override fun value2(): LocalDateTime? = issuedAt
    override fun value3(): LocalDateTime? = expiresAt
    override fun value4(): LocalDateTime? = authenticatedAt
    override fun value5(): UUID? = identityId
    override fun value6(): LocalDateTime? = createdAt
    override fun value7(): LocalDateTime? = updatedAt
    override fun value8(): String? = token
    override fun value9(): Boolean? = active
    override fun value10(): UUID? = nid
    override fun value11(): String? = logoutToken
    override fun value12(): String? = aal
    override fun value13(): JSONB? = authenticationMethods

    override fun value1(value: UUID?): SessionsRecord {
        this.id = value
        return this
    }

    override fun value2(value: LocalDateTime?): SessionsRecord {
        this.issuedAt = value
        return this
    }

    override fun value3(value: LocalDateTime?): SessionsRecord {
        this.expiresAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): SessionsRecord {
        this.authenticatedAt = value
        return this
    }

    override fun value5(value: UUID?): SessionsRecord {
        this.identityId = value
        return this
    }

    override fun value6(value: LocalDateTime?): SessionsRecord {
        this.createdAt = value
        return this
    }

    override fun value7(value: LocalDateTime?): SessionsRecord {
        this.updatedAt = value
        return this
    }

    override fun value8(value: String?): SessionsRecord {
        this.token = value
        return this
    }

    override fun value9(value: Boolean?): SessionsRecord {
        this.active = value
        return this
    }

    override fun value10(value: UUID?): SessionsRecord {
        this.nid = value
        return this
    }

    override fun value11(value: String?): SessionsRecord {
        this.logoutToken = value
        return this
    }

    override fun value12(value: String?): SessionsRecord {
        this.aal = value
        return this
    }

    override fun value13(value: JSONB?): SessionsRecord {
        this.authenticationMethods = value
        return this
    }

    override fun values(value1: UUID?, value2: LocalDateTime?, value3: LocalDateTime?, value4: LocalDateTime?, value5: UUID?, value6: LocalDateTime?, value7: LocalDateTime?, value8: String?, value9: Boolean?, value10: UUID?, value11: String?, value12: String?, value13: JSONB?): SessionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    constructor(id: UUID? = null, issuedAt: LocalDateTime? = null, expiresAt: LocalDateTime? = null, authenticatedAt: LocalDateTime? = null, identityId: UUID? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, token: String? = null, active: Boolean? = null, nid: UUID? = null, logoutToken: String? = null, aal: String? = null, authenticationMethods: JSONB? = null): this() {
        this.id = id
        this.issuedAt = issuedAt
        this.expiresAt = expiresAt
        this.authenticatedAt = authenticatedAt
        this.identityId = identityId
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.token = token
        this.active = active
        this.nid = nid
        this.logoutToken = logoutToken
        this.aal = aal
        this.authenticationMethods = authenticationMethods
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Sessions?): this() {
        if (value != null) {
            this.id = value.id
            this.issuedAt = value.issuedAt
            this.expiresAt = value.expiresAt
            this.authenticatedAt = value.authenticatedAt
            this.identityId = value.identityId
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.token = value.token
            this.active = value.active
            this.nid = value.nid
            this.logoutToken = value.logoutToken
            this.aal = value.aal
            this.authenticationMethods = value.authenticationMethods
        }
    }
}
