/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.records


import ch.yass.db.tables.Trick

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TrickRecord() : UpdatableRecordImpl<TrickRecord>(Trick.TRICK), Record7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var uuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updatedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var handId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var winnerId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var points: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?> = super.fieldsRow() as Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?>
    override fun valuesRow(): Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?> = super.valuesRow() as Row7<Int?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = Trick.TRICK.ID
    override fun field2(): Field<String?> = Trick.TRICK.UUID
    override fun field3(): Field<LocalDateTime?> = Trick.TRICK.CREATED_AT
    override fun field4(): Field<LocalDateTime?> = Trick.TRICK.UPDATED_AT
    override fun field5(): Field<Int?> = Trick.TRICK.HAND_ID
    override fun field6(): Field<Int?> = Trick.TRICK.WINNER_ID
    override fun field7(): Field<Int?> = Trick.TRICK.POINTS
    override fun component1(): Int? = id
    override fun component2(): String? = uuid
    override fun component3(): LocalDateTime? = createdAt
    override fun component4(): LocalDateTime? = updatedAt
    override fun component5(): Int? = handId
    override fun component6(): Int? = winnerId
    override fun component7(): Int? = points
    override fun value1(): Int? = id
    override fun value2(): String? = uuid
    override fun value3(): LocalDateTime? = createdAt
    override fun value4(): LocalDateTime? = updatedAt
    override fun value5(): Int? = handId
    override fun value6(): Int? = winnerId
    override fun value7(): Int? = points

    override fun value1(value: Int?): TrickRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TrickRecord {
        this.uuid = value
        return this
    }

    override fun value3(value: LocalDateTime?): TrickRecord {
        this.createdAt = value
        return this
    }

    override fun value4(value: LocalDateTime?): TrickRecord {
        this.updatedAt = value
        return this
    }

    override fun value5(value: Int?): TrickRecord {
        this.handId = value
        return this
    }

    override fun value6(value: Int?): TrickRecord {
        this.winnerId = value
        return this
    }

    override fun value7(value: Int?): TrickRecord {
        this.points = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?, value5: Int?, value6: Int?, value7: Int?): TrickRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(id: Int? = null, uuid: String? = null, createdAt: LocalDateTime? = null, updatedAt: LocalDateTime? = null, handId: Int? = null, winnerId: Int? = null, points: Int? = null): this() {
        this.id = id
        this.uuid = uuid
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.handId = handId
        this.winnerId = winnerId
        this.points = points
    }

    /**
     * Create a detached, initialised TrickRecord
     */
    constructor(value: ch.yass.db.tables.pojos.Trick?): this() {
        if (value != null) {
            this.id = value.id
            this.uuid = value.uuid
            this.createdAt = value.createdAt
            this.updatedAt = value.updatedAt
            this.handId = value.handId
            this.winnerId = value.winnerId
            this.points = value.points
        }
    }
}
