/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.Arrays
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CourierMessages(
    var id: UUID? = null,
    var type: Int? = null,
    var status: Int? = null,
    var body: String? = null,
    var subject: String? = null,
    var recipient: String? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var templateType: String? = null,
    var templateData: ByteArray? = null,
    var nid: UUID? = null,
    var sendCount: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: CourierMessages = other as CourierMessages
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.type === null) {
            if (o.type !== null)
                return false
        }
        else if (this.type != o.type)
            return false
        if (this.status === null) {
            if (o.status !== null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.body === null) {
            if (o.body !== null)
                return false
        }
        else if (this.body != o.body)
            return false
        if (this.subject === null) {
            if (o.subject !== null)
                return false
        }
        else if (this.subject != o.subject)
            return false
        if (this.recipient === null) {
            if (o.recipient !== null)
                return false
        }
        else if (this.recipient != o.recipient)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        if (this.templateType === null) {
            if (o.templateType !== null)
                return false
        }
        else if (this.templateType != o.templateType)
            return false
        if (this.templateData === null) {
            if (o.templateData !== null)
                return false
        }
        else if (!Arrays.equals(this.templateData, o.templateData))
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        if (this.sendCount === null) {
            if (o.sendCount !== null)
                return false
        }
        else if (this.sendCount != o.sendCount)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.type === null) 0 else this.type.hashCode())
        result = prime * result + (if (this.status === null) 0 else this.status.hashCode())
        result = prime * result + (if (this.body === null) 0 else this.body.hashCode())
        result = prime * result + (if (this.subject === null) 0 else this.subject.hashCode())
        result = prime * result + (if (this.recipient === null) 0 else this.recipient.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        result = prime * result + (if (this.templateType === null) 0 else this.templateType.hashCode())
        result = prime * result + (if (this.templateData === null) 0 else Arrays.hashCode(this.templateData))
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        result = prime * result + (if (this.sendCount === null) 0 else this.sendCount.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CourierMessages (")

        sb.append(id)
        sb.append(", ").append(type)
        sb.append(", ").append(status)
        sb.append(", ").append(body)
        sb.append(", ").append(subject)
        sb.append(", ").append(recipient)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(templateType)
        sb.append(", ").append("[binary...]")
        sb.append(", ").append(nid)
        sb.append(", ").append(sendCount)

        sb.append(")")
        return sb.toString()
    }
}
