/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSON


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CourierMessageDispatches(
    var id: UUID? = null,
    var messageId: UUID? = null,
    var status: String? = null,
    var error: JSON? = null,
    var nid: UUID? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: CourierMessageDispatches = other as CourierMessageDispatches
        if (this.id === null) {
            if (o.id !== null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.messageId === null) {
            if (o.messageId !== null)
                return false
        }
        else if (this.messageId != o.messageId)
            return false
        if (this.status === null) {
            if (o.status !== null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.error === null) {
            if (o.error !== null)
                return false
        }
        else if (this.error != o.error)
            return false
        if (this.nid === null) {
            if (o.nid !== null)
                return false
        }
        else if (this.nid != o.nid)
            return false
        if (this.createdAt === null) {
            if (o.createdAt !== null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt === null) {
            if (o.updatedAt !== null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id === null) 0 else this.id.hashCode())
        result = prime * result + (if (this.messageId === null) 0 else this.messageId.hashCode())
        result = prime * result + (if (this.status === null) 0 else this.status.hashCode())
        result = prime * result + (if (this.error === null) 0 else this.error.hashCode())
        result = prime * result + (if (this.nid === null) 0 else this.nid.hashCode())
        result = prime * result + (if (this.createdAt === null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt === null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CourierMessageDispatches (")

        sb.append(id)
        sb.append(", ").append(messageId)
        sb.append(", ").append(status)
        sb.append(", ").append(error)
        sb.append(", ").append(nid)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
