/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDate
import java.time.LocalDateTime

import org.jooq.JSON


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class DailyChallenge(
    var id: Int,
    var uuid: String,
    var createdAt: LocalDateTime,
    var updatedAt: LocalDateTime,
    var day: LocalDate,
    var seed: Long,
    var forcedDecks: JSON? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: DailyChallenge = other as DailyChallenge
        if (this.id != o.id)
            return false
        if (this.uuid != o.uuid)
            return false
        if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt != o.updatedAt)
            return false
        if (this.day != o.day)
            return false
        if (this.seed != o.seed)
            return false
        if (this.forcedDecks == null) {
            if (o.forcedDecks != null)
                return false
        }
        else if (this.forcedDecks != o.forcedDecks)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.uuid.hashCode()
        result = prime * result + this.createdAt.hashCode()
        result = prime * result + this.updatedAt.hashCode()
        result = prime * result + this.day.hashCode()
        result = prime * result + this.seed.hashCode()
        result = prime * result + (if (this.forcedDecks == null) 0 else this.forcedDecks.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("DailyChallenge (")

        sb.append(id)
        sb.append(", ").append(uuid)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(day)
        sb.append(", ").append(seed)
        sb.append(", ").append(forcedDecks)

        sb.append(")")
        return sb.toString()
    }
}
