/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime

import org.jooq.JSON


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Game(
    var id: Int? = null,
    var uuid: String,
    var createdAt: LocalDateTime,
    var updatedAt: LocalDateTime,
    var code: String,
    var settings: JSON? = null,
    var status: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Game = other as Game
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.uuid != o.uuid)
            return false
        if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt != o.updatedAt)
            return false
        if (this.code != o.code)
            return false
        if (this.settings == null) {
            if (o.settings != null)
                return false
        }
        else if (this.settings != o.settings)
            return false
        if (this.status == null) {
            if (o.status != null)
                return false
        }
        else if (this.status != o.status)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.uuid.hashCode()
        result = prime * result + this.createdAt.hashCode()
        result = prime * result + this.updatedAt.hashCode()
        result = prime * result + this.code.hashCode()
        result = prime * result + (if (this.settings == null) 0 else this.settings.hashCode())
        result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Game (")

        sb.append(id)
        sb.append(", ").append(uuid)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(code)
        sb.append(", ").append(settings)
        sb.append(", ").append(status)

        sb.append(")")
        return sb.toString()
    }
}
