/*
 * This file is generated by jOOQ.
 */
package ch.yass.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime

import org.jooq.JSON


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Hand(
    var id: Int? = null,
    var uuid: String,
    var createdAt: LocalDateTime,
    var updatedAt: LocalDateTime,
    var gameId: Int,
    var trump: String? = null,
    var gschobe: String,
    var north: JSON,
    var east: JSON,
    var south: JSON,
    var west: JSON,
    var northWeise: JSON? = null,
    var eastWeise: JSON? = null,
    var southWeise: JSON? = null,
    var westWeise: JSON? = null,
    var startingPosition: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Hand = other as Hand
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.uuid != o.uuid)
            return false
        if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt != o.updatedAt)
            return false
        if (this.gameId != o.gameId)
            return false
        if (this.trump == null) {
            if (o.trump != null)
                return false
        }
        else if (this.trump != o.trump)
            return false
        if (this.gschobe != o.gschobe)
            return false
        if (this.north != o.north)
            return false
        if (this.east != o.east)
            return false
        if (this.south != o.south)
            return false
        if (this.west != o.west)
            return false
        if (this.northWeise == null) {
            if (o.northWeise != null)
                return false
        }
        else if (this.northWeise != o.northWeise)
            return false
        if (this.eastWeise == null) {
            if (o.eastWeise != null)
                return false
        }
        else if (this.eastWeise != o.eastWeise)
            return false
        if (this.southWeise == null) {
            if (o.southWeise != null)
                return false
        }
        else if (this.southWeise != o.southWeise)
            return false
        if (this.westWeise == null) {
            if (o.westWeise != null)
                return false
        }
        else if (this.westWeise != o.westWeise)
            return false
        if (this.startingPosition == null) {
            if (o.startingPosition != null)
                return false
        }
        else if (this.startingPosition != o.startingPosition)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.uuid.hashCode()
        result = prime * result + this.createdAt.hashCode()
        result = prime * result + this.updatedAt.hashCode()
        result = prime * result + this.gameId.hashCode()
        result = prime * result + (if (this.trump == null) 0 else this.trump.hashCode())
        result = prime * result + this.gschobe.hashCode()
        result = prime * result + this.north.hashCode()
        result = prime * result + this.east.hashCode()
        result = prime * result + this.south.hashCode()
        result = prime * result + this.west.hashCode()
        result = prime * result + (if (this.northWeise == null) 0 else this.northWeise.hashCode())
        result = prime * result + (if (this.eastWeise == null) 0 else this.eastWeise.hashCode())
        result = prime * result + (if (this.southWeise == null) 0 else this.southWeise.hashCode())
        result = prime * result + (if (this.westWeise == null) 0 else this.westWeise.hashCode())
        result = prime * result + (if (this.startingPosition == null) 0 else this.startingPosition.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Hand (")

        sb.append(id)
        sb.append(", ").append(uuid)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)
        sb.append(", ").append(gameId)
        sb.append(", ").append(trump)
        sb.append(", ").append(gschobe)
        sb.append(", ").append(north)
        sb.append(", ").append(east)
        sb.append(", ").append(south)
        sb.append(", ").append(west)
        sb.append(", ").append(northWeise)
        sb.append(", ").append(eastWeise)
        sb.append(", ").append(southWeise)
        sb.append(", ").append(westWeise)
        sb.append(", ").append(startingPosition)

        sb.append(")")
        return sb.toString()
    }
}
